import type { CreatureManifest } from '@/lib/creatures/schema'

export type LocalCreatureBlueprint = CreatureManifest & { catalogId: string }

export const localCreatureCatalog = [
  {
    "catalogId": "local-001",
    "name": "Moussibulle",
    "rarity": "common",
    "description": "Moussibulle est une créature toute ronde qui aime les fleurs hautes et marche à petits pas.",
    "personality": "curieuse et douce",
    "biome": "meadow",
    "movementType": "walking",
    "bodyShape": "round",
    "earShape": "round",
    "tailShape": "curl",
    "pattern": "freckles",
    "palette": {
      "primary": "#8EE6C8",
      "secondary": "#F7D6FF",
      "accent": "#FFE66D",
      "dark": "#315C55"
    },
    "visuals": {
      "eyeStyle": "sleepy",
      "mouthStyle": "cat",
      "wingStyle": "none",
      "antennaStyle": "dots",
      "legStyle": "tiny",
      "auraStyle": "moon_glow",
      "size": "tiny",
      "tilt": -2
    },
    "parts": [
      "body",
      "wings",
      "sparkles",
      "eyes",
      "spots",
      "horns",
      "mouth",
      "belly",
      "crest",
      "ears",
      "antennae",
      "shadow_glow"
    ]
  },
  {
    "catalogId": "local-002",
    "name": "Brindibulle",
    "rarity": "rare",
    "description": "Brindibulle est une créature champignon qui aime les champignons doux et sautille sans bruit.",
    "personality": "malicieuse mais très tendre",
    "biome": "mushroom_grove",
    "movementType": "hopping",
    "bodyShape": "mushroom",
    "earShape": "none",
    "tailShape": "leaf",
    "pattern": "waves",
    "palette": {
      "primary": "#A5D86A",
      "secondary": "#FFF1A8",
      "accent": "#FF9FB2",
      "dark": "#3C6134"
    },
    "visuals": {
      "eyeStyle": "wide",
      "mouthStyle": "smile",
      "wingStyle": "leaf",
      "antennaStyle": "none",
      "legStyle": "leafy",
      "auraStyle": "sparkles",
      "size": "large",
      "tilt": -1
    },
    "parts": [
      "body",
      "horns",
      "antennae",
      "tail",
      "eyes",
      "crest",
      "cheeks",
      "wings",
      "mouth",
      "shadow_glow",
      "aura",
      "spots"
    ]
  },
  {
    "catalogId": "local-003",
    "name": "Lumibulle",
    "rarity": "uncommon",
    "description": "Lumibulle est une créature galet vivant qui aime les mares brillantes et vole lentement.",
    "personality": "rêveuse et calme",
    "biome": "pond",
    "movementType": "flying",
    "bodyShape": "pebble",
    "earShape": "petal",
    "tailShape": "glow",
    "pattern": "stripes",
    "palette": {
      "primary": "#A4C8FF",
      "secondary": "#F2E6FF",
      "accent": "#FFD166",
      "dark": "#334767"
    },
    "visuals": {
      "eyeStyle": "dot",
      "mouthStyle": "beak",
      "wingStyle": "butterfly",
      "antennaStyle": "curl",
      "legStyle": "webbed",
      "auraStyle": "none",
      "size": "medium",
      "tilt": 0
    },
    "parts": [
      "body",
      "spots",
      "crest",
      "legs",
      "aura",
      "eyes",
      "belly",
      "shadow_glow",
      "tail",
      "sparkles",
      "mouth",
      "antennae"
    ]
  },
  {
    "catalogId": "local-004",
    "name": "Ploofbulle",
    "rarity": "common",
    "description": "Ploofbulle est une créature nuageuse qui aime les clairières de lune et flotte comme un rêve.",
    "personality": "timide et brillante",
    "biome": "moon_clearing",
    "movementType": "floating",
    "bodyShape": "cloud",
    "earShape": "horns",
    "tailShape": "none",
    "pattern": "leaf_veins",
    "palette": {
      "primary": "#D9A7FF",
      "secondary": "#B8F2E6",
      "accent": "#FFCF70",
      "dark": "#4C3A68"
    },
    "visuals": {
      "eyeStyle": "round",
      "mouthStyle": "tiny",
      "wingStyle": "none",
      "antennaStyle": "stars",
      "legStyle": "none",
      "auraStyle": "pollen",
      "size": "small",
      "tilt": 1
    },
    "parts": [
      "body",
      "ears",
      "wings",
      "antennae",
      "sparkles",
      "shadow_glow",
      "eyes",
      "legs",
      "spots",
      "cheeks",
      "horns",
      "mouth"
    ]
  },
  {
    "catalogId": "local-005",
    "name": "Nébulibulle",
    "rarity": "wonder",
    "description": "Nébulibulle est une créature feuillue qui aime les mares brillantes et nage dans les reflets.",
    "personality": "joyeuse et sautillante",
    "biome": "pond",
    "movementType": "swimming",
    "bodyShape": "leaf",
    "earShape": "leaf",
    "tailShape": "ribbon",
    "pattern": "moon",
    "palette": {
      "primary": "#FFB7A3",
      "secondary": "#FFF3C4",
      "accent": "#8EE3EF",
      "dark": "#70403B"
    },
    "visuals": {
      "eyeStyle": "sparkle",
      "mouthStyle": "none",
      "wingStyle": "leaf",
      "antennaStyle": "leaves",
      "legStyle": "none",
      "auraStyle": "bubbles",
      "size": "tiny",
      "tilt": 2
    },
    "parts": [
      "body",
      "tail",
      "cheeks",
      "shadow_glow",
      "ears",
      "belly",
      "horns",
      "eyes",
      "wings",
      "aura",
      "legs",
      "antennae"
    ]
  },
  {
    "catalogId": "local-006",
    "name": "Roselibulle",
    "rarity": "uncommon",
    "description": "Roselibulle est une créature étoilée qui aime les mares brillantes et passe de la berge à l’eau.",
    "personality": "bizarre juste comme il faut",
    "biome": "pond",
    "movementType": "amphibious",
    "bodyShape": "star",
    "earShape": "tuft",
    "tailShape": "puff",
    "pattern": "rings",
    "palette": {
      "primary": "#7BDFF2",
      "secondary": "#C2F8CB",
      "accent": "#F7D794",
      "dark": "#28536B"
    },
    "visuals": {
      "eyeStyle": "crescent",
      "mouthStyle": "cat",
      "wingStyle": "moth",
      "antennaStyle": "dots",
      "legStyle": "tiny",
      "auraStyle": "mist",
      "size": "large",
      "tilt": -2
    },
    "parts": [
      "body",
      "shadow_glow",
      "horns",
      "aura",
      "antennae",
      "spots",
      "tail",
      "ears",
      "eyes",
      "crest",
      "sparkles",
      "cheeks"
    ]
  },
  {
    "catalogId": "local-007",
    "name": "Bamboubulle",
    "rarity": "common",
    "description": "Bamboubulle est une créature coquillage doux qui aime les clairières de lune et sautille sans bruit.",
    "personality": "nocturne et rassurante",
    "biome": "moon_clearing",
    "movementType": "hopping",
    "bodyShape": "shell",
    "earShape": "fin",
    "tailShape": "star",
    "pattern": "spots",
    "palette": {
      "primary": "#B8E986",
      "secondary": "#E7FBBE",
      "accent": "#FFB6C1",
      "dark": "#365B2D"
    },
    "visuals": {
      "eyeStyle": "glow",
      "mouthStyle": "smile",
      "wingStyle": "none",
      "antennaStyle": "none",
      "legStyle": "leafy",
      "auraStyle": "moon_glow",
      "size": "medium",
      "tilt": -1
    },
    "parts": [
      "body",
      "mouth",
      "legs",
      "wings",
      "belly",
      "cheeks",
      "sparkles",
      "crest",
      "eyes",
      "ears",
      "tail",
      "spots"
    ]
  },
  {
    "catalogId": "local-008",
    "name": "Floribulle",
    "rarity": "common",
    "description": "Floribulle est une créature en forme de haricot qui aime les petits bois et vole lentement.",
    "personality": "gourmande de pollen",
    "biome": "forest",
    "movementType": "flying",
    "bodyShape": "bean",
    "earShape": "round",
    "tailShape": "fin",
    "pattern": "stars",
    "palette": {
      "primary": "#CDB4DB",
      "secondary": "#FFC8DD",
      "accent": "#BDE0FE",
      "dark": "#4A3A57"
    },
    "visuals": {
      "eyeStyle": "sleepy",
      "mouthStyle": "beak",
      "wingStyle": "butterfly",
      "antennaStyle": "curl",
      "legStyle": "webbed",
      "auraStyle": "sparkles",
      "size": "small",
      "tilt": 0
    },
    "parts": [
      "body",
      "sparkles",
      "spots",
      "mouth",
      "crest",
      "antennae",
      "legs",
      "aura",
      "wings",
      "eyes",
      "horns",
      "belly"
    ]
  },
  {
    "catalogId": "local-009",
    "name": "Dodubulle",
    "rarity": "rare",
    "description": "Dodubulle est une créature gouttelette qui aime les mares brillantes et flotte comme un rêve.",
    "personality": "protectrice des petites pousses",
    "biome": "pond",
    "movementType": "floating",
    "bodyShape": "droplet",
    "earShape": "none",
    "tailShape": "curl",
    "pattern": "none",
    "palette": {
      "primary": "#F4A261",
      "secondary": "#E9C46A",
      "accent": "#2A9D8F",
      "dark": "#5A3A1E"
    },
    "visuals": {
      "eyeStyle": "wide",
      "mouthStyle": "tiny",
      "wingStyle": "moth",
      "antennaStyle": "stars",
      "legStyle": "none",
      "auraStyle": "none",
      "size": "tiny",
      "tilt": 1
    },
    "parts": [
      "body",
      "crest",
      "aura",
      "belly",
      "tail",
      "mouth",
      "horns",
      "cheeks",
      "spots",
      "legs",
      "eyes",
      "shadow_glow"
    ]
  },
  {
    "catalogId": "local-010",
    "name": "Ziboubulle",
    "rarity": "uncommon",
    "description": "Ziboubulle est une créature toute longue qui aime les mares brillantes et nage dans les reflets.",
    "personality": "amusante et jamais pressée",
    "biome": "pond",
    "movementType": "swimming",
    "bodyShape": "long",
    "earShape": "petal",
    "tailShape": "leaf",
    "pattern": "freckles",
    "palette": {
      "primary": "#90BE6D",
      "secondary": "#F9C74F",
      "accent": "#577590",
      "dark": "#334E37"
    },
    "visuals": {
      "eyeStyle": "dot",
      "mouthStyle": "none",
      "wingStyle": "none",
      "antennaStyle": "leaves",
      "legStyle": "none",
      "auraStyle": "pollen",
      "size": "large",
      "tilt": 2
    },
    "parts": [
      "body",
      "cheeks",
      "ears",
      "horns",
      "wings",
      "antennae",
      "mouth",
      "sparkles",
      "tail",
      "shadow_glow",
      "belly",
      "eyes"
    ]
  },
  {
    "catalogId": "local-011",
    "name": "Mirobulle",
    "rarity": "common",
    "description": "Mirobulle est une créature toute ronde qui aime les mares brillantes et passe de la berge à l’eau.",
    "personality": "curieuse et douce",
    "biome": "pond",
    "movementType": "amphibious",
    "bodyShape": "round",
    "earShape": "horns",
    "tailShape": "glow",
    "pattern": "waves",
    "palette": {
      "primary": "#C8E7FF",
      "secondary": "#FFF6BF",
      "accent": "#B392F0",
      "dark": "#2B3A67"
    },
    "visuals": {
      "eyeStyle": "round",
      "mouthStyle": "cat",
      "wingStyle": "leaf",
      "antennaStyle": "dots",
      "legStyle": "tiny",
      "auraStyle": "bubbles",
      "size": "medium",
      "tilt": -2
    },
    "parts": [
      "body",
      "eyes",
      "legs",
      "belly",
      "sparkles",
      "ears",
      "spots",
      "aura",
      "shadow_glow",
      "mouth",
      "wings",
      "cheeks"
    ]
  },
  {
    "catalogId": "local-012",
    "name": "Plumibulle",
    "rarity": "wonder",
    "description": "Plumibulle est une créature champignon qui aime les fleurs hautes et marche à petits pas.",
    "personality": "malicieuse mais très tendre",
    "biome": "meadow",
    "movementType": "walking",
    "bodyShape": "mushroom",
    "earShape": "leaf",
    "tailShape": "none",
    "pattern": "stripes",
    "palette": {
      "primary": "#A0E7E5",
      "secondary": "#B4F8C8",
      "accent": "#FBE7C6",
      "dark": "#28544B"
    },
    "visuals": {
      "eyeStyle": "sparkle",
      "mouthStyle": "smile",
      "wingStyle": "moth",
      "antennaStyle": "none",
      "legStyle": "leafy",
      "auraStyle": "mist",
      "size": "small",
      "tilt": -1
    },
    "parts": [
      "body",
      "eyes",
      "aura",
      "tail",
      "cheeks",
      "legs",
      "shadow_glow",
      "antennae",
      "ears",
      "crest",
      "belly",
      "mouth"
    ]
  },
  {
    "catalogId": "local-013",
    "name": "Tintibulle",
    "rarity": "uncommon",
    "description": "Tintibulle est une créature galet vivant qui aime les clairières de lune et vole lentement.",
    "personality": "rêveuse et calme",
    "biome": "moon_clearing",
    "movementType": "flying",
    "bodyShape": "pebble",
    "earShape": "tuft",
    "tailShape": "ribbon",
    "pattern": "leaf_veins",
    "palette": {
      "primary": "#F7A9A8",
      "secondary": "#FDE2E4",
      "accent": "#CDEAC0",
      "dark": "#643843"
    },
    "visuals": {
      "eyeStyle": "crescent",
      "mouthStyle": "beak",
      "wingStyle": "butterfly",
      "antennaStyle": "curl",
      "legStyle": "webbed",
      "auraStyle": "moon_glow",
      "size": "tiny",
      "tilt": 0
    },
    "parts": [
      "body",
      "eyes",
      "belly",
      "spots",
      "shadow_glow",
      "wings",
      "crest",
      "tail",
      "horns",
      "legs",
      "sparkles",
      "ears"
    ]
  },
  {
    "catalogId": "local-014",
    "name": "Glimbulle",
    "rarity": "common",
    "description": "Glimbulle est une créature nuageuse qui aime les petits bois et flotte comme un rêve.",
    "personality": "timide et brillante",
    "biome": "forest",
    "movementType": "floating",
    "bodyShape": "cloud",
    "earShape": "fin",
    "tailShape": "puff",
    "pattern": "moon",
    "palette": {
      "primary": "#9D4EDD",
      "secondary": "#E0AAFF",
      "accent": "#80FFDB",
      "dark": "#3C096C"
    },
    "visuals": {
      "eyeStyle": "glow",
      "mouthStyle": "tiny",
      "wingStyle": "leaf",
      "antennaStyle": "stars",
      "legStyle": "none",
      "auraStyle": "sparkles",
      "size": "large",
      "tilt": 1
    },
    "parts": [
      "body",
      "eyes",
      "shadow_glow",
      "crest",
      "horns",
      "sparkles",
      "aura",
      "cheeks",
      "antennae",
      "belly",
      "spots",
      "wings"
    ]
  },
  {
    "catalogId": "local-015",
    "name": "Mallowbulle",
    "rarity": "common",
    "description": "Mallowbulle est une créature feuillue qui aime les mares brillantes et nage dans les reflets.",
    "personality": "joyeuse et sautillante",
    "biome": "pond",
    "movementType": "swimming",
    "bodyShape": "leaf",
    "earShape": "round",
    "tailShape": "star",
    "pattern": "rings",
    "palette": {
      "primary": "#577590",
      "secondary": "#F3CA40",
      "accent": "#F2A541",
      "dark": "#25364A"
    },
    "visuals": {
      "eyeStyle": "sleepy",
      "mouthStyle": "none",
      "wingStyle": "moth",
      "antennaStyle": "leaves",
      "legStyle": "none",
      "auraStyle": "none",
      "size": "medium",
      "tilt": 2
    },
    "parts": [
      "body",
      "eyes",
      "mouth",
      "ears",
      "legs",
      "tail",
      "wings",
      "spots",
      "belly",
      "antennae",
      "cheeks",
      "aura"
    ]
  },
  {
    "catalogId": "local-016",
    "name": "Froubulle",
    "rarity": "rare",
    "description": "Froubulle est une créature étoilée qui aime les champignons doux et passe de la berge à l’eau.",
    "personality": "bizarre juste comme il faut",
    "biome": "mushroom_grove",
    "movementType": "amphibious",
    "bodyShape": "star",
    "earShape": "none",
    "tailShape": "fin",
    "pattern": "spots",
    "palette": {
      "primary": "#84DCC6",
      "secondary": "#A5FFD6",
      "accent": "#FFA69E",
      "dark": "#355C55"
    },
    "visuals": {
      "eyeStyle": "wide",
      "mouthStyle": "cat",
      "wingStyle": "none",
      "antennaStyle": "dots",
      "legStyle": "tiny",
      "auraStyle": "pollen",
      "size": "small",
      "tilt": -2
    },
    "parts": [
      "body",
      "eyes",
      "mouth",
      "ears",
      "legs",
      "tail",
      "wings",
      "spots",
      "belly",
      "antennae",
      "cheeks",
      "aura"
    ]
  },
  {
    "catalogId": "local-017",
    "name": "Sissibulle",
    "rarity": "uncommon",
    "description": "Sissibulle est une créature coquillage doux qui aime les petits bois et marche à petits pas.",
    "personality": "nocturne et rassurante",
    "biome": "forest",
    "movementType": "walking",
    "bodyShape": "shell",
    "earShape": "petal",
    "tailShape": "curl",
    "pattern": "stars",
    "palette": {
      "primary": "#BFD7EA",
      "secondary": "#F5E6E8",
      "accent": "#F4B860",
      "dark": "#2F4858"
    },
    "visuals": {
      "eyeStyle": "dot",
      "mouthStyle": "smile",
      "wingStyle": "leaf",
      "antennaStyle": "none",
      "legStyle": "leafy",
      "auraStyle": "bubbles",
      "size": "tiny",
      "tilt": -1
    },
    "parts": [
      "body",
      "antennae",
      "eyes",
      "cheeks",
      "mouth",
      "aura",
      "ears",
      "sparkles",
      "legs",
      "horns",
      "tail",
      "crest"
    ]
  },
  {
    "catalogId": "local-018",
    "name": "Bloopbulle",
    "rarity": "common",
    "description": "Bloopbulle est une créature en forme de haricot qui aime les fleurs hautes et sautille sans bruit.",
    "personality": "gourmande de pollen",
    "biome": "meadow",
    "movementType": "hopping",
    "bodyShape": "bean",
    "earShape": "horns",
    "tailShape": "leaf",
    "pattern": "none",
    "palette": {
      "primary": "#D0F4DE",
      "secondary": "#FCF6BD",
      "accent": "#A9DEF9",
      "dark": "#3E5C43"
    },
    "visuals": {
      "eyeStyle": "round",
      "mouthStyle": "beak",
      "wingStyle": "moth",
      "antennaStyle": "curl",
      "legStyle": "webbed",
      "auraStyle": "mist",
      "size": "large",
      "tilt": 0
    },
    "parts": [
      "body",
      "wings",
      "sparkles",
      "eyes",
      "spots",
      "horns",
      "mouth",
      "belly",
      "crest",
      "ears",
      "antennae",
      "shadow_glow"
    ]
  },
  {
    "catalogId": "local-019",
    "name": "Noctibulle",
    "rarity": "wonder",
    "description": "Noctibulle est une créature gouttelette qui aime les champignons doux et flotte comme un rêve.",
    "personality": "protectrice des petites pousses",
    "biome": "mushroom_grove",
    "movementType": "floating",
    "bodyShape": "droplet",
    "earShape": "leaf",
    "tailShape": "glow",
    "pattern": "freckles",
    "palette": {
      "primary": "#E4C1F9",
      "secondary": "#F694C1",
      "accent": "#EDE7B1",
      "dark": "#543864"
    },
    "visuals": {
      "eyeStyle": "sparkle",
      "mouthStyle": "tiny",
      "wingStyle": "none",
      "antennaStyle": "stars",
      "legStyle": "none",
      "auraStyle": "moon_glow",
      "size": "medium",
      "tilt": 1
    },
    "parts": [
      "body",
      "horns",
      "antennae",
      "tail",
      "eyes",
      "crest",
      "cheeks",
      "wings",
      "mouth",
      "shadow_glow",
      "aura",
      "spots"
    ]
  },
  {
    "catalogId": "local-020",
    "name": "Pépibulle",
    "rarity": "uncommon",
    "description": "Pépibulle est une créature toute longue qui aime les mares brillantes et nage dans les reflets.",
    "personality": "amusante et jamais pressée",
    "biome": "pond",
    "movementType": "swimming",
    "bodyShape": "long",
    "earShape": "tuft",
    "tailShape": "none",
    "pattern": "waves",
    "palette": {
      "primary": "#CDE7BE",
      "secondary": "#F3FFBD",
      "accent": "#FFB3C1",
      "dark": "#3B5B42"
    },
    "visuals": {
      "eyeStyle": "crescent",
      "mouthStyle": "none",
      "wingStyle": "leaf",
      "antennaStyle": "leaves",
      "legStyle": "none",
      "auraStyle": "sparkles",
      "size": "small",
      "tilt": 2
    },
    "parts": [
      "body",
      "spots",
      "crest",
      "legs",
      "aura",
      "eyes",
      "belly",
      "shadow_glow",
      "tail",
      "sparkles",
      "mouth",
      "antennae"
    ]
  },
  {
    "catalogId": "local-021",
    "name": "Moussilune",
    "rarity": "common",
    "description": "Moussilune est une créature toute ronde qui aime les mares brillantes et passe de la berge à l’eau.",
    "personality": "curieuse et douce",
    "biome": "pond",
    "movementType": "amphibious",
    "bodyShape": "round",
    "earShape": "fin",
    "tailShape": "ribbon",
    "pattern": "stripes",
    "palette": {
      "primary": "#8EE6C8",
      "secondary": "#F7D6FF",
      "accent": "#FFE66D",
      "dark": "#315C55"
    },
    "visuals": {
      "eyeStyle": "glow",
      "mouthStyle": "cat",
      "wingStyle": "moth",
      "antennaStyle": "dots",
      "legStyle": "tiny",
      "auraStyle": "none",
      "size": "tiny",
      "tilt": -2
    },
    "parts": [
      "body",
      "ears",
      "wings",
      "antennae",
      "sparkles",
      "shadow_glow",
      "eyes",
      "legs",
      "spots",
      "cheeks",
      "horns",
      "mouth"
    ]
  },
  {
    "catalogId": "local-022",
    "name": "Brindilune",
    "rarity": "common",
    "description": "Brindilune est une créature champignon qui aime les champignons doux et marche à petits pas.",
    "personality": "malicieuse mais très tendre",
    "biome": "mushroom_grove",
    "movementType": "walking",
    "bodyShape": "mushroom",
    "earShape": "round",
    "tailShape": "puff",
    "pattern": "leaf_veins",
    "palette": {
      "primary": "#A5D86A",
      "secondary": "#FFF1A8",
      "accent": "#FF9FB2",
      "dark": "#3C6134"
    },
    "visuals": {
      "eyeStyle": "sleepy",
      "mouthStyle": "smile",
      "wingStyle": "none",
      "antennaStyle": "none",
      "legStyle": "leafy",
      "auraStyle": "pollen",
      "size": "large",
      "tilt": -1
    },
    "parts": [
      "body",
      "tail",
      "cheeks",
      "shadow_glow",
      "ears",
      "belly",
      "horns",
      "eyes",
      "wings",
      "aura",
      "legs",
      "antennae"
    ]
  },
  {
    "catalogId": "local-023",
    "name": "Lumilune",
    "rarity": "rare",
    "description": "Lumilune est une créature galet vivant qui aime les mares brillantes et sautille sans bruit.",
    "personality": "rêveuse et calme",
    "biome": "pond",
    "movementType": "hopping",
    "bodyShape": "pebble",
    "earShape": "none",
    "tailShape": "star",
    "pattern": "moon",
    "palette": {
      "primary": "#A4C8FF",
      "secondary": "#F2E6FF",
      "accent": "#FFD166",
      "dark": "#334767"
    },
    "visuals": {
      "eyeStyle": "wide",
      "mouthStyle": "beak",
      "wingStyle": "leaf",
      "antennaStyle": "curl",
      "legStyle": "webbed",
      "auraStyle": "bubbles",
      "size": "medium",
      "tilt": 0
    },
    "parts": [
      "body",
      "shadow_glow",
      "horns",
      "aura",
      "antennae",
      "spots",
      "tail",
      "ears",
      "eyes",
      "crest",
      "sparkles",
      "cheeks"
    ]
  },
  {
    "catalogId": "local-024",
    "name": "Plooflune",
    "rarity": "uncommon",
    "description": "Plooflune est une créature nuageuse qui aime les clairières de lune et vole lentement.",
    "personality": "timide et brillante",
    "biome": "moon_clearing",
    "movementType": "flying",
    "bodyShape": "cloud",
    "earShape": "petal",
    "tailShape": "fin",
    "pattern": "rings",
    "palette": {
      "primary": "#D9A7FF",
      "secondary": "#B8F2E6",
      "accent": "#FFCF70",
      "dark": "#4C3A68"
    },
    "visuals": {
      "eyeStyle": "dot",
      "mouthStyle": "tiny",
      "wingStyle": "moth",
      "antennaStyle": "stars",
      "legStyle": "none",
      "auraStyle": "mist",
      "size": "small",
      "tilt": 1
    },
    "parts": [
      "body",
      "mouth",
      "legs",
      "wings",
      "belly",
      "cheeks",
      "sparkles",
      "crest",
      "eyes",
      "ears",
      "tail",
      "spots"
    ]
  },
  {
    "catalogId": "local-025",
    "name": "Nébulilune",
    "rarity": "common",
    "description": "Nébulilune est une créature feuillue qui aime les mares brillantes et nage dans les reflets.",
    "personality": "joyeuse et sautillante",
    "biome": "pond",
    "movementType": "swimming",
    "bodyShape": "leaf",
    "earShape": "horns",
    "tailShape": "curl",
    "pattern": "spots",
    "palette": {
      "primary": "#FFB7A3",
      "secondary": "#FFF3C4",
      "accent": "#8EE3EF",
      "dark": "#70403B"
    },
    "visuals": {
      "eyeStyle": "round",
      "mouthStyle": "none",
      "wingStyle": "none",
      "antennaStyle": "leaves",
      "legStyle": "none",
      "auraStyle": "moon_glow",
      "size": "tiny",
      "tilt": 2
    },
    "parts": [
      "body",
      "sparkles",
      "spots",
      "mouth",
      "crest",
      "antennae",
      "legs",
      "aura",
      "wings",
      "eyes",
      "horns",
      "belly"
    ]
  },
  {
    "catalogId": "local-026",
    "name": "Roselilune",
    "rarity": "wonder",
    "description": "Roselilune est une créature étoilée qui aime les mares brillantes et passe de la berge à l’eau.",
    "personality": "bizarre juste comme il faut",
    "biome": "pond",
    "movementType": "amphibious",
    "bodyShape": "star",
    "earShape": "leaf",
    "tailShape": "leaf",
    "pattern": "stars",
    "palette": {
      "primary": "#7BDFF2",
      "secondary": "#C2F8CB",
      "accent": "#F7D794",
      "dark": "#28536B"
    },
    "visuals": {
      "eyeStyle": "sparkle",
      "mouthStyle": "cat",
      "wingStyle": "leaf",
      "antennaStyle": "dots",
      "legStyle": "tiny",
      "auraStyle": "sparkles",
      "size": "large",
      "tilt": -2
    },
    "parts": [
      "body",
      "crest",
      "aura",
      "belly",
      "tail",
      "mouth",
      "horns",
      "cheeks",
      "spots",
      "legs",
      "eyes",
      "shadow_glow"
    ]
  },
  {
    "catalogId": "local-027",
    "name": "Bamboulune",
    "rarity": "uncommon",
    "description": "Bamboulune est une créature coquillage doux qui aime les clairières de lune et marche à petits pas.",
    "personality": "nocturne et rassurante",
    "biome": "moon_clearing",
    "movementType": "walking",
    "bodyShape": "shell",
    "earShape": "tuft",
    "tailShape": "glow",
    "pattern": "none",
    "palette": {
      "primary": "#B8E986",
      "secondary": "#E7FBBE",
      "accent": "#FFB6C1",
      "dark": "#365B2D"
    },
    "visuals": {
      "eyeStyle": "crescent",
      "mouthStyle": "smile",
      "wingStyle": "moth",
      "antennaStyle": "none",
      "legStyle": "leafy",
      "auraStyle": "none",
      "size": "medium",
      "tilt": -1
    },
    "parts": [
      "body",
      "cheeks",
      "ears",
      "horns",
      "wings",
      "antennae",
      "mouth",
      "sparkles",
      "tail",
      "shadow_glow",
      "belly",
      "eyes"
    ]
  },
  {
    "catalogId": "local-028",
    "name": "Florilune",
    "rarity": "common",
    "description": "Florilune est une créature en forme de haricot qui aime les petits bois et sautille sans bruit.",
    "personality": "gourmande de pollen",
    "biome": "forest",
    "movementType": "hopping",
    "bodyShape": "bean",
    "earShape": "fin",
    "tailShape": "none",
    "pattern": "freckles",
    "palette": {
      "primary": "#CDB4DB",
      "secondary": "#FFC8DD",
      "accent": "#BDE0FE",
      "dark": "#4A3A57"
    },
    "visuals": {
      "eyeStyle": "glow",
      "mouthStyle": "beak",
      "wingStyle": "none",
      "antennaStyle": "curl",
      "legStyle": "webbed",
      "auraStyle": "pollen",
      "size": "small",
      "tilt": 0
    },
    "parts": [
      "body",
      "eyes",
      "legs",
      "belly",
      "sparkles",
      "ears",
      "spots",
      "aura",
      "shadow_glow",
      "mouth",
      "wings",
      "cheeks"
    ]
  },
  {
    "catalogId": "local-029",
    "name": "Dodulune",
    "rarity": "common",
    "description": "Dodulune est une créature gouttelette qui aime les mares brillantes et vole lentement.",
    "personality": "protectrice des petites pousses",
    "biome": "pond",
    "movementType": "flying",
    "bodyShape": "droplet",
    "earShape": "round",
    "tailShape": "ribbon",
    "pattern": "waves",
    "palette": {
      "primary": "#F4A261",
      "secondary": "#E9C46A",
      "accent": "#2A9D8F",
      "dark": "#5A3A1E"
    },
    "visuals": {
      "eyeStyle": "sleepy",
      "mouthStyle": "tiny",
      "wingStyle": "moth",
      "antennaStyle": "stars",
      "legStyle": "none",
      "auraStyle": "bubbles",
      "size": "tiny",
      "tilt": 1
    },
    "parts": [
      "body",
      "eyes",
      "aura",
      "tail",
      "cheeks",
      "legs",
      "shadow_glow",
      "antennae",
      "ears",
      "crest",
      "belly",
      "mouth"
    ]
  },
  {
    "catalogId": "local-030",
    "name": "Ziboulune",
    "rarity": "rare",
    "description": "Ziboulune est une créature toute longue qui aime les clairières de lune et flotte comme un rêve.",
    "personality": "amusante et jamais pressée",
    "biome": "moon_clearing",
    "movementType": "floating",
    "bodyShape": "long",
    "earShape": "none",
    "tailShape": "puff",
    "pattern": "stripes",
    "palette": {
      "primary": "#90BE6D",
      "secondary": "#F9C74F",
      "accent": "#577590",
      "dark": "#334E37"
    },
    "visuals": {
      "eyeStyle": "wide",
      "mouthStyle": "none",
      "wingStyle": "moth",
      "antennaStyle": "leaves",
      "legStyle": "none",
      "auraStyle": "mist",
      "size": "large",
      "tilt": 2
    },
    "parts": [
      "body",
      "eyes",
      "belly",
      "spots",
      "shadow_glow",
      "wings",
      "crest",
      "tail",
      "horns",
      "legs",
      "sparkles",
      "ears"
    ]
  },
  {
    "catalogId": "local-031",
    "name": "Mirolune",
    "rarity": "uncommon",
    "description": "Mirolune est une créature toute ronde qui aime les mares brillantes et passe de la berge à l’eau.",
    "personality": "curieuse et douce",
    "biome": "pond",
    "movementType": "amphibious",
    "bodyShape": "round",
    "earShape": "petal",
    "tailShape": "star",
    "pattern": "leaf_veins",
    "palette": {
      "primary": "#C8E7FF",
      "secondary": "#FFF6BF",
      "accent": "#B392F0",
      "dark": "#2B3A67"
    },
    "visuals": {
      "eyeStyle": "dot",
      "mouthStyle": "cat",
      "wingStyle": "none",
      "antennaStyle": "dots",
      "legStyle": "tiny",
      "auraStyle": "moon_glow",
      "size": "medium",
      "tilt": -2
    },
    "parts": [
      "body",
      "eyes",
      "shadow_glow",
      "crest",
      "horns",
      "sparkles",
      "aura",
      "cheeks",
      "antennae",
      "belly",
      "spots",
      "wings"
    ]
  },
  {
    "catalogId": "local-032",
    "name": "Plumilune",
    "rarity": "common",
    "description": "Plumilune est une créature champignon qui aime les fleurs hautes et marche à petits pas.",
    "personality": "malicieuse mais très tendre",
    "biome": "meadow",
    "movementType": "walking",
    "bodyShape": "mushroom",
    "earShape": "horns",
    "tailShape": "fin",
    "pattern": "moon",
    "palette": {
      "primary": "#A0E7E5",
      "secondary": "#B4F8C8",
      "accent": "#FBE7C6",
      "dark": "#28544B"
    },
    "visuals": {
      "eyeStyle": "round",
      "mouthStyle": "smile",
      "wingStyle": "leaf",
      "antennaStyle": "none",
      "legStyle": "leafy",
      "auraStyle": "sparkles",
      "size": "small",
      "tilt": -1
    },
    "parts": [
      "body",
      "eyes",
      "mouth",
      "ears",
      "legs",
      "tail",
      "wings",
      "spots",
      "belly",
      "antennae",
      "cheeks",
      "aura"
    ]
  },
  {
    "catalogId": "local-033",
    "name": "Tintilune",
    "rarity": "wonder",
    "description": "Tintilune est une créature galet vivant qui aime les clairières de lune et sautille sans bruit.",
    "personality": "rêveuse et calme",
    "biome": "moon_clearing",
    "movementType": "hopping",
    "bodyShape": "pebble",
    "earShape": "leaf",
    "tailShape": "curl",
    "pattern": "rings",
    "palette": {
      "primary": "#F7A9A8",
      "secondary": "#FDE2E4",
      "accent": "#CDEAC0",
      "dark": "#643843"
    },
    "visuals": {
      "eyeStyle": "sparkle",
      "mouthStyle": "beak",
      "wingStyle": "moth",
      "antennaStyle": "curl",
      "legStyle": "webbed",
      "auraStyle": "none",
      "size": "tiny",
      "tilt": 0
    },
    "parts": [
      "body",
      "eyes",
      "mouth",
      "ears",
      "legs",
      "tail",
      "wings",
      "spots",
      "belly",
      "antennae",
      "cheeks",
      "aura"
    ]
  },
  {
    "catalogId": "local-034",
    "name": "Glimlune",
    "rarity": "uncommon",
    "description": "Glimlune est une créature nuageuse qui aime les petits bois et vole lentement.",
    "personality": "timide et brillante",
    "biome": "forest",
    "movementType": "flying",
    "bodyShape": "cloud",
    "earShape": "tuft",
    "tailShape": "leaf",
    "pattern": "spots",
    "palette": {
      "primary": "#9D4EDD",
      "secondary": "#E0AAFF",
      "accent": "#80FFDB",
      "dark": "#3C096C"
    },
    "visuals": {
      "eyeStyle": "crescent",
      "mouthStyle": "tiny",
      "wingStyle": "moth",
      "antennaStyle": "stars",
      "legStyle": "none",
      "auraStyle": "pollen",
      "size": "large",
      "tilt": 1
    },
    "parts": [
      "body",
      "antennae",
      "eyes",
      "cheeks",
      "mouth",
      "aura",
      "ears",
      "sparkles",
      "legs",
      "horns",
      "tail",
      "crest"
    ]
  },
  {
    "catalogId": "local-035",
    "name": "Mallowlune",
    "rarity": "common",
    "description": "Mallowlune est une créature feuillue qui aime les fleurs hautes et flotte comme un rêve.",
    "personality": "joyeuse et sautillante",
    "biome": "meadow",
    "movementType": "floating",
    "bodyShape": "leaf",
    "earShape": "fin",
    "tailShape": "glow",
    "pattern": "stars",
    "palette": {
      "primary": "#577590",
      "secondary": "#F3CA40",
      "accent": "#F2A541",
      "dark": "#25364A"
    },
    "visuals": {
      "eyeStyle": "glow",
      "mouthStyle": "none",
      "wingStyle": "leaf",
      "antennaStyle": "leaves",
      "legStyle": "none",
      "auraStyle": "bubbles",
      "size": "medium",
      "tilt": 2
    },
    "parts": [
      "body",
      "wings",
      "sparkles",
      "eyes",
      "spots",
      "horns",
      "mouth",
      "belly",
      "crest",
      "ears",
      "antennae",
      "shadow_glow"
    ]
  },
  {
    "catalogId": "local-036",
    "name": "Froulune",
    "rarity": "common",
    "description": "Froulune est une créature étoilée qui aime les mares brillantes et nage dans les reflets.",
    "personality": "bizarre juste comme il faut",
    "biome": "pond",
    "movementType": "swimming",
    "bodyShape": "star",
    "earShape": "round",
    "tailShape": "none",
    "pattern": "none",
    "palette": {
      "primary": "#84DCC6",
      "secondary": "#A5FFD6",
      "accent": "#FFA69E",
      "dark": "#355C55"
    },
    "visuals": {
      "eyeStyle": "sleepy",
      "mouthStyle": "cat",
      "wingStyle": "moth",
      "antennaStyle": "dots",
      "legStyle": "none",
      "auraStyle": "mist",
      "size": "small",
      "tilt": -2
    },
    "parts": [
      "body",
      "horns",
      "antennae",
      "tail",
      "eyes",
      "crest",
      "cheeks",
      "wings",
      "mouth",
      "shadow_glow",
      "aura",
      "spots"
    ]
  },
  {
    "catalogId": "local-037",
    "name": "Sissilune",
    "rarity": "rare",
    "description": "Sissilune est une créature coquillage doux qui aime les petits bois et marche à petits pas.",
    "personality": "nocturne et rassurante",
    "biome": "forest",
    "movementType": "walking",
    "bodyShape": "shell",
    "earShape": "none",
    "tailShape": "ribbon",
    "pattern": "freckles",
    "palette": {
      "primary": "#BFD7EA",
      "secondary": "#F5E6E8",
      "accent": "#F4B860",
      "dark": "#2F4858"
    },
    "visuals": {
      "eyeStyle": "wide",
      "mouthStyle": "smile",
      "wingStyle": "none",
      "antennaStyle": "none",
      "legStyle": "leafy",
      "auraStyle": "moon_glow",
      "size": "tiny",
      "tilt": -1
    },
    "parts": [
      "body",
      "spots",
      "crest",
      "legs",
      "aura",
      "eyes",
      "belly",
      "shadow_glow",
      "tail",
      "sparkles",
      "mouth",
      "antennae"
    ]
  },
  {
    "catalogId": "local-038",
    "name": "Blooplune",
    "rarity": "uncommon",
    "description": "Blooplune est une créature en forme de haricot qui aime les fleurs hautes et sautille sans bruit.",
    "personality": "gourmande de pollen",
    "biome": "meadow",
    "movementType": "hopping",
    "bodyShape": "bean",
    "earShape": "petal",
    "tailShape": "puff",
    "pattern": "waves",
    "palette": {
      "primary": "#D0F4DE",
      "secondary": "#FCF6BD",
      "accent": "#A9DEF9",
      "dark": "#3E5C43"
    },
    "visuals": {
      "eyeStyle": "dot",
      "mouthStyle": "beak",
      "wingStyle": "leaf",
      "antennaStyle": "curl",
      "legStyle": "webbed",
      "auraStyle": "sparkles",
      "size": "large",
      "tilt": 0
    },
    "parts": [
      "body",
      "ears",
      "wings",
      "antennae",
      "sparkles",
      "shadow_glow",
      "eyes",
      "legs",
      "spots",
      "cheeks",
      "horns",
      "mouth"
    ]
  },
  {
    "catalogId": "local-039",
    "name": "Noctilune",
    "rarity": "common",
    "description": "Noctilune est une créature gouttelette qui aime les champignons doux et vole lentement.",
    "personality": "protectrice des petites pousses",
    "biome": "mushroom_grove",
    "movementType": "flying",
    "bodyShape": "droplet",
    "earShape": "horns",
    "tailShape": "star",
    "pattern": "stripes",
    "palette": {
      "primary": "#E4C1F9",
      "secondary": "#F694C1",
      "accent": "#EDE7B1",
      "dark": "#543864"
    },
    "visuals": {
      "eyeStyle": "round",
      "mouthStyle": "tiny",
      "wingStyle": "moth",
      "antennaStyle": "stars",
      "legStyle": "none",
      "auraStyle": "none",
      "size": "medium",
      "tilt": 1
    },
    "parts": [
      "body",
      "tail",
      "cheeks",
      "shadow_glow",
      "ears",
      "belly",
      "horns",
      "eyes",
      "wings",
      "aura",
      "legs",
      "antennae"
    ]
  },
  {
    "catalogId": "local-040",
    "name": "Pépilune",
    "rarity": "wonder",
    "description": "Pépilune est une créature toute longue qui aime les mares brillantes et flotte comme un rêve.",
    "personality": "amusante et jamais pressée",
    "biome": "pond",
    "movementType": "floating",
    "bodyShape": "long",
    "earShape": "leaf",
    "tailShape": "fin",
    "pattern": "leaf_veins",
    "palette": {
      "primary": "#CDE7BE",
      "secondary": "#F3FFBD",
      "accent": "#FFB3C1",
      "dark": "#3B5B42"
    },
    "visuals": {
      "eyeStyle": "sparkle",
      "mouthStyle": "none",
      "wingStyle": "none",
      "antennaStyle": "leaves",
      "legStyle": "none",
      "auraStyle": "pollen",
      "size": "small",
      "tilt": 2
    },
    "parts": [
      "body",
      "shadow_glow",
      "horns",
      "aura",
      "antennae",
      "spots",
      "tail",
      "ears",
      "eyes",
      "crest",
      "sparkles",
      "cheeks"
    ]
  },
  {
    "catalogId": "local-041",
    "name": "Moussimoussea",
    "rarity": "uncommon",
    "description": "Moussimoussea est une créature toute ronde qui aime les mares brillantes et nage dans les reflets.",
    "personality": "curieuse et douce",
    "biome": "pond",
    "movementType": "swimming",
    "bodyShape": "round",
    "earShape": "tuft",
    "tailShape": "curl",
    "pattern": "moon",
    "palette": {
      "primary": "#8EE6C8",
      "secondary": "#F7D6FF",
      "accent": "#FFE66D",
      "dark": "#315C55"
    },
    "visuals": {
      "eyeStyle": "crescent",
      "mouthStyle": "cat",
      "wingStyle": "leaf",
      "antennaStyle": "dots",
      "legStyle": "none",
      "auraStyle": "bubbles",
      "size": "tiny",
      "tilt": -2
    },
    "parts": [
      "body",
      "mouth",
      "legs",
      "wings",
      "belly",
      "cheeks",
      "sparkles",
      "crest",
      "eyes",
      "ears",
      "tail",
      "spots"
    ]
  },
  {
    "catalogId": "local-042",
    "name": "Brindimoussei",
    "rarity": "common",
    "description": "Brindimoussei est une créature champignon qui aime les champignons doux et passe de la berge à l’eau.",
    "personality": "malicieuse mais très tendre",
    "biome": "mushroom_grove",
    "movementType": "amphibious",
    "bodyShape": "mushroom",
    "earShape": "fin",
    "tailShape": "leaf",
    "pattern": "rings",
    "palette": {
      "primary": "#A5D86A",
      "secondary": "#FFF1A8",
      "accent": "#FF9FB2",
      "dark": "#3C6134"
    },
    "visuals": {
      "eyeStyle": "glow",
      "mouthStyle": "smile",
      "wingStyle": "moth",
      "antennaStyle": "none",
      "legStyle": "leafy",
      "auraStyle": "mist",
      "size": "large",
      "tilt": -1
    },
    "parts": [
      "body",
      "sparkles",
      "spots",
      "mouth",
      "crest",
      "antennae",
      "legs",
      "aura",
      "wings",
      "eyes",
      "horns",
      "belly"
    ]
  },
  {
    "catalogId": "local-043",
    "name": "Lumimousseo",
    "rarity": "common",
    "description": "Lumimousseo est une créature galet vivant qui aime les mares brillantes et sautille sans bruit.",
    "personality": "rêveuse et calme",
    "biome": "pond",
    "movementType": "hopping",
    "bodyShape": "pebble",
    "earShape": "round",
    "tailShape": "glow",
    "pattern": "spots",
    "palette": {
      "primary": "#A4C8FF",
      "secondary": "#F2E6FF",
      "accent": "#FFD166",
      "dark": "#334767"
    },
    "visuals": {
      "eyeStyle": "sleepy",
      "mouthStyle": "beak",
      "wingStyle": "none",
      "antennaStyle": "curl",
      "legStyle": "webbed",
      "auraStyle": "moon_glow",
      "size": "medium",
      "tilt": 0
    },
    "parts": [
      "body",
      "crest",
      "aura",
      "belly",
      "tail",
      "mouth",
      "horns",
      "cheeks",
      "spots",
      "legs",
      "eyes",
      "shadow_glow"
    ]
  },
  {
    "catalogId": "local-044",
    "name": "Ploofmousseu",
    "rarity": "rare",
    "description": "Ploofmousseu est une créature nuageuse qui aime les clairières de lune et vole lentement.",
    "personality": "timide et brillante",
    "biome": "moon_clearing",
    "movementType": "flying",
    "bodyShape": "cloud",
    "earShape": "none",
    "tailShape": "none",
    "pattern": "stars",
    "palette": {
      "primary": "#D9A7FF",
      "secondary": "#B8F2E6",
      "accent": "#FFCF70",
      "dark": "#4C3A68"
    },
    "visuals": {
      "eyeStyle": "wide",
      "mouthStyle": "tiny",
      "wingStyle": "moth",
      "antennaStyle": "stars",
      "legStyle": "none",
      "auraStyle": "sparkles",
      "size": "small",
      "tilt": 1
    },
    "parts": [
      "body",
      "cheeks",
      "ears",
      "horns",
      "wings",
      "antennae",
      "mouth",
      "sparkles",
      "tail",
      "shadow_glow",
      "belly",
      "eyes"
    ]
  },
  {
    "catalogId": "local-045",
    "name": "Nébulimousseé",
    "rarity": "uncommon",
    "description": "Nébulimousseé est une créature feuillue qui aime les champignons doux et flotte comme un rêve.",
    "personality": "joyeuse et sautillante",
    "biome": "mushroom_grove",
    "movementType": "floating",
    "bodyShape": "leaf",
    "earShape": "petal",
    "tailShape": "ribbon",
    "pattern": "none",
    "palette": {
      "primary": "#FFB7A3",
      "secondary": "#FFF3C4",
      "accent": "#8EE3EF",
      "dark": "#70403B"
    },
    "visuals": {
      "eyeStyle": "dot",
      "mouthStyle": "none",
      "wingStyle": "moth",
      "antennaStyle": "leaves",
      "legStyle": "none",
      "auraStyle": "none",
      "size": "tiny",
      "tilt": 2
    },
    "parts": [
      "body",
      "eyes",
      "legs",
      "belly",
      "sparkles",
      "ears",
      "spots",
      "aura",
      "shadow_glow",
      "mouth",
      "wings",
      "cheeks"
    ]
  },
  {
    "catalogId": "local-046",
    "name": "Roselimoussea",
    "rarity": "common",
    "description": "Roselimoussea est une créature étoilée qui aime les mares brillantes et nage dans les reflets.",
    "personality": "bizarre juste comme il faut",
    "biome": "pond",
    "movementType": "swimming",
    "bodyShape": "star",
    "earShape": "horns",
    "tailShape": "puff",
    "pattern": "freckles",
    "palette": {
      "primary": "#7BDFF2",
      "secondary": "#C2F8CB",
      "accent": "#F7D794",
      "dark": "#28536B"
    },
    "visuals": {
      "eyeStyle": "round",
      "mouthStyle": "cat",
      "wingStyle": "none",
      "antennaStyle": "dots",
      "legStyle": "none",
      "auraStyle": "pollen",
      "size": "large",
      "tilt": -2
    },
    "parts": [
      "body",
      "eyes",
      "aura",
      "tail",
      "cheeks",
      "legs",
      "shadow_glow",
      "antennae",
      "ears",
      "crest",
      "belly",
      "mouth"
    ]
  },
  {
    "catalogId": "local-047",
    "name": "Bamboumoussei",
    "rarity": "wonder",
    "description": "Bamboumoussei est une créature coquillage doux qui aime les mares brillantes et passe de la berge à l’eau.",
    "personality": "nocturne et rassurante",
    "biome": "pond",
    "movementType": "amphibious",
    "bodyShape": "shell",
    "earShape": "leaf",
    "tailShape": "star",
    "pattern": "waves",
    "palette": {
      "primary": "#B8E986",
      "secondary": "#E7FBBE",
      "accent": "#FFB6C1",
      "dark": "#365B2D"
    },
    "visuals": {
      "eyeStyle": "sparkle",
      "mouthStyle": "smile",
      "wingStyle": "leaf",
      "antennaStyle": "none",
      "legStyle": "leafy",
      "auraStyle": "bubbles",
      "size": "medium",
      "tilt": -1
    },
    "parts": [
      "body",
      "eyes",
      "belly",
      "spots",
      "shadow_glow",
      "wings",
      "crest",
      "tail",
      "horns",
      "legs",
      "sparkles",
      "ears"
    ]
  },
  {
    "catalogId": "local-048",
    "name": "Florimousseo",
    "rarity": "uncommon",
    "description": "Florimousseo est une créature en forme de haricot qui aime les petits bois et marche à petits pas.",
    "personality": "gourmande de pollen",
    "biome": "forest",
    "movementType": "walking",
    "bodyShape": "bean",
    "earShape": "tuft",
    "tailShape": "fin",
    "pattern": "stripes",
    "palette": {
      "primary": "#CDB4DB",
      "secondary": "#FFC8DD",
      "accent": "#BDE0FE",
      "dark": "#4A3A57"
    },
    "visuals": {
      "eyeStyle": "crescent",
      "mouthStyle": "beak",
      "wingStyle": "moth",
      "antennaStyle": "curl",
      "legStyle": "webbed",
      "auraStyle": "mist",
      "size": "small",
      "tilt": 0
    },
    "parts": [
      "body",
      "eyes",
      "shadow_glow",
      "crest",
      "horns",
      "sparkles",
      "aura",
      "cheeks",
      "antennae",
      "belly",
      "spots",
      "wings"
    ]
  },
  {
    "catalogId": "local-049",
    "name": "Dodumousseu",
    "rarity": "common",
    "description": "Dodumousseu est une créature gouttelette qui aime les mares brillantes et vole lentement.",
    "personality": "protectrice des petites pousses",
    "biome": "pond",
    "movementType": "flying",
    "bodyShape": "droplet",
    "earShape": "fin",
    "tailShape": "curl",
    "pattern": "leaf_veins",
    "palette": {
      "primary": "#F4A261",
      "secondary": "#E9C46A",
      "accent": "#2A9D8F",
      "dark": "#5A3A1E"
    },
    "visuals": {
      "eyeStyle": "glow",
      "mouthStyle": "tiny",
      "wingStyle": "moth",
      "antennaStyle": "stars",
      "legStyle": "none",
      "auraStyle": "moon_glow",
      "size": "tiny",
      "tilt": 1
    },
    "parts": [
      "body",
      "eyes",
      "mouth",
      "ears",
      "legs",
      "tail",
      "wings",
      "spots",
      "belly",
      "antennae",
      "cheeks",
      "aura"
    ]
  },
  {
    "catalogId": "local-050",
    "name": "Ziboumousseé",
    "rarity": "common",
    "description": "Ziboumousseé est une créature toute longue qui aime les clairières de lune et flotte comme un rêve.",
    "personality": "amusante et jamais pressée",
    "biome": "moon_clearing",
    "movementType": "floating",
    "bodyShape": "long",
    "earShape": "round",
    "tailShape": "leaf",
    "pattern": "moon",
    "palette": {
      "primary": "#90BE6D",
      "secondary": "#F9C74F",
      "accent": "#577590",
      "dark": "#334E37"
    },
    "visuals": {
      "eyeStyle": "sleepy",
      "mouthStyle": "none",
      "wingStyle": "leaf",
      "antennaStyle": "leaves",
      "legStyle": "none",
      "auraStyle": "sparkles",
      "size": "large",
      "tilt": 2
    },
    "parts": [
      "body",
      "eyes",
      "mouth",
      "ears",
      "legs",
      "tail",
      "wings",
      "spots",
      "belly",
      "antennae",
      "cheeks",
      "aura"
    ]
  },
  {
    "catalogId": "local-051",
    "name": "Miromoussea",
    "rarity": "rare",
    "description": "Miromoussea est une créature toute ronde qui aime les mares brillantes et nage dans les reflets.",
    "personality": "curieuse et douce",
    "biome": "pond",
    "movementType": "swimming",
    "bodyShape": "round",
    "earShape": "none",
    "tailShape": "glow",
    "pattern": "rings",
    "palette": {
      "primary": "#C8E7FF",
      "secondary": "#FFF6BF",
      "accent": "#B392F0",
      "dark": "#2B3A67"
    },
    "visuals": {
      "eyeStyle": "wide",
      "mouthStyle": "cat",
      "wingStyle": "moth",
      "antennaStyle": "dots",
      "legStyle": "none",
      "auraStyle": "none",
      "size": "medium",
      "tilt": -2
    },
    "parts": [
      "body",
      "antennae",
      "eyes",
      "cheeks",
      "mouth",
      "aura",
      "ears",
      "sparkles",
      "legs",
      "horns",
      "tail",
      "crest"
    ]
  },
  {
    "catalogId": "local-052",
    "name": "Plumimoussei",
    "rarity": "uncommon",
    "description": "Plumimoussei est une créature champignon qui aime les fleurs hautes et passe de la berge à l’eau.",
    "personality": "malicieuse mais très tendre",
    "biome": "meadow",
    "movementType": "amphibious",
    "bodyShape": "mushroom",
    "earShape": "petal",
    "tailShape": "none",
    "pattern": "spots",
    "palette": {
      "primary": "#A0E7E5",
      "secondary": "#B4F8C8",
      "accent": "#FBE7C6",
      "dark": "#28544B"
    },
    "visuals": {
      "eyeStyle": "dot",
      "mouthStyle": "smile",
      "wingStyle": "none",
      "antennaStyle": "none",
      "legStyle": "leafy",
      "auraStyle": "pollen",
      "size": "small",
      "tilt": -1
    },
    "parts": [
      "body",
      "wings",
      "sparkles",
      "eyes",
      "spots",
      "horns",
      "mouth",
      "belly",
      "crest",
      "ears",
      "antennae",
      "shadow_glow"
    ]
  },
  {
    "catalogId": "local-053",
    "name": "Tintimousseo",
    "rarity": "common",
    "description": "Tintimousseo est une créature galet vivant qui aime les clairières de lune et marche à petits pas.",
    "personality": "rêveuse et calme",
    "biome": "moon_clearing",
    "movementType": "walking",
    "bodyShape": "pebble",
    "earShape": "horns",
    "tailShape": "ribbon",
    "pattern": "stars",
    "palette": {
      "primary": "#F7A9A8",
      "secondary": "#FDE2E4",
      "accent": "#CDEAC0",
      "dark": "#643843"
    },
    "visuals": {
      "eyeStyle": "round",
      "mouthStyle": "beak",
      "wingStyle": "leaf",
      "antennaStyle": "curl",
      "legStyle": "webbed",
      "auraStyle": "bubbles",
      "size": "tiny",
      "tilt": 0
    },
    "parts": [
      "body",
      "horns",
      "antennae",
      "tail",
      "eyes",
      "crest",
      "cheeks",
      "wings",
      "mouth",
      "shadow_glow",
      "aura",
      "spots"
    ]
  },
  {
    "catalogId": "local-054",
    "name": "Glimmousseu",
    "rarity": "wonder",
    "description": "Glimmousseu est une créature nuageuse qui aime les petits bois et sautille sans bruit.",
    "personality": "timide et brillante",
    "biome": "forest",
    "movementType": "hopping",
    "bodyShape": "cloud",
    "earShape": "leaf",
    "tailShape": "puff",
    "pattern": "none",
    "palette": {
      "primary": "#9D4EDD",
      "secondary": "#E0AAFF",
      "accent": "#80FFDB",
      "dark": "#3C096C"
    },
    "visuals": {
      "eyeStyle": "sparkle",
      "mouthStyle": "tiny",
      "wingStyle": "moth",
      "antennaStyle": "stars",
      "legStyle": "none",
      "auraStyle": "mist",
      "size": "large",
      "tilt": 1
    },
    "parts": [
      "body",
      "spots",
      "crest",
      "legs",
      "aura",
      "eyes",
      "belly",
      "shadow_glow",
      "tail",
      "sparkles",
      "mouth",
      "antennae"
    ]
  },
  {
    "catalogId": "local-055",
    "name": "Mallowmousseé",
    "rarity": "uncommon",
    "description": "Mallowmousseé est une créature feuillue qui aime les fleurs hautes et flotte comme un rêve.",
    "personality": "joyeuse et sautillante",
    "biome": "meadow",
    "movementType": "floating",
    "bodyShape": "leaf",
    "earShape": "tuft",
    "tailShape": "star",
    "pattern": "freckles",
    "palette": {
      "primary": "#577590",
      "secondary": "#F3CA40",
      "accent": "#F2A541",
      "dark": "#25364A"
    },
    "visuals": {
      "eyeStyle": "crescent",
      "mouthStyle": "none",
      "wingStyle": "none",
      "antennaStyle": "leaves",
      "legStyle": "none",
      "auraStyle": "moon_glow",
      "size": "medium",
      "tilt": 2
    },
    "parts": [
      "body",
      "ears",
      "wings",
      "antennae",
      "sparkles",
      "shadow_glow",
      "eyes",
      "legs",
      "spots",
      "cheeks",
      "horns",
      "mouth"
    ]
  },
  {
    "catalogId": "local-056",
    "name": "Froumoussea",
    "rarity": "common",
    "description": "Froumoussea est une créature étoilée qui aime les mares brillantes et nage dans les reflets.",
    "personality": "bizarre juste comme il faut",
    "biome": "pond",
    "movementType": "swimming",
    "bodyShape": "star",
    "earShape": "fin",
    "tailShape": "fin",
    "pattern": "waves",
    "palette": {
      "primary": "#84DCC6",
      "secondary": "#A5FFD6",
      "accent": "#FFA69E",
      "dark": "#355C55"
    },
    "visuals": {
      "eyeStyle": "glow",
      "mouthStyle": "cat",
      "wingStyle": "leaf",
      "antennaStyle": "dots",
      "legStyle": "none",
      "auraStyle": "sparkles",
      "size": "small",
      "tilt": -2
    },
    "parts": [
      "body",
      "tail",
      "cheeks",
      "shadow_glow",
      "ears",
      "belly",
      "horns",
      "eyes",
      "wings",
      "aura",
      "legs",
      "antennae"
    ]
  },
  {
    "catalogId": "local-057",
    "name": "Sissimoussei",
    "rarity": "common",
    "description": "Sissimoussei est une créature coquillage doux qui aime les mares brillantes et passe de la berge à l’eau.",
    "personality": "nocturne et rassurante",
    "biome": "pond",
    "movementType": "amphibious",
    "bodyShape": "shell",
    "earShape": "round",
    "tailShape": "curl",
    "pattern": "stripes",
    "palette": {
      "primary": "#BFD7EA",
      "secondary": "#F5E6E8",
      "accent": "#F4B860",
      "dark": "#2F4858"
    },
    "visuals": {
      "eyeStyle": "sleepy",
      "mouthStyle": "smile",
      "wingStyle": "moth",
      "antennaStyle": "none",
      "legStyle": "leafy",
      "auraStyle": "none",
      "size": "tiny",
      "tilt": -1
    },
    "parts": [
      "body",
      "shadow_glow",
      "horns",
      "aura",
      "antennae",
      "spots",
      "tail",
      "ears",
      "eyes",
      "crest",
      "sparkles",
      "cheeks"
    ]
  },
  {
    "catalogId": "local-058",
    "name": "Bloopmousseo",
    "rarity": "rare",
    "description": "Bloopmousseo est une créature en forme de haricot qui aime les fleurs hautes et marche à petits pas.",
    "personality": "gourmande de pollen",
    "biome": "meadow",
    "movementType": "walking",
    "bodyShape": "bean",
    "earShape": "none",
    "tailShape": "leaf",
    "pattern": "leaf_veins",
    "palette": {
      "primary": "#D0F4DE",
      "secondary": "#FCF6BD",
      "accent": "#A9DEF9",
      "dark": "#3E5C43"
    },
    "visuals": {
      "eyeStyle": "wide",
      "mouthStyle": "beak",
      "wingStyle": "none",
      "antennaStyle": "curl",
      "legStyle": "webbed",
      "auraStyle": "pollen",
      "size": "large",
      "tilt": 0
    },
    "parts": [
      "body",
      "mouth",
      "legs",
      "wings",
      "belly",
      "cheeks",
      "sparkles",
      "crest",
      "eyes",
      "ears",
      "tail",
      "spots"
    ]
  },
  {
    "catalogId": "local-059",
    "name": "Noctimousseu",
    "rarity": "uncommon",
    "description": "Noctimousseu est une créature gouttelette qui aime les champignons doux et sautille sans bruit.",
    "personality": "protectrice des petites pousses",
    "biome": "mushroom_grove",
    "movementType": "hopping",
    "bodyShape": "droplet",
    "earShape": "petal",
    "tailShape": "glow",
    "pattern": "moon",
    "palette": {
      "primary": "#E4C1F9",
      "secondary": "#F694C1",
      "accent": "#EDE7B1",
      "dark": "#543864"
    },
    "visuals": {
      "eyeStyle": "dot",
      "mouthStyle": "tiny",
      "wingStyle": "leaf",
      "antennaStyle": "stars",
      "legStyle": "none",
      "auraStyle": "bubbles",
      "size": "medium",
      "tilt": 1
    },
    "parts": [
      "body",
      "sparkles",
      "spots",
      "mouth",
      "crest",
      "antennae",
      "legs",
      "aura",
      "wings",
      "eyes",
      "horns",
      "belly"
    ]
  },
  {
    "catalogId": "local-060",
    "name": "Pépimousseé",
    "rarity": "common",
    "description": "Pépimousseé est une créature toute longue qui aime les mares brillantes et vole lentement.",
    "personality": "amusante et jamais pressée",
    "biome": "pond",
    "movementType": "flying",
    "bodyShape": "long",
    "earShape": "horns",
    "tailShape": "none",
    "pattern": "rings",
    "palette": {
      "primary": "#CDE7BE",
      "secondary": "#F3FFBD",
      "accent": "#FFB3C1",
      "dark": "#3B5B42"
    },
    "visuals": {
      "eyeStyle": "round",
      "mouthStyle": "none",
      "wingStyle": "bubble",
      "antennaStyle": "leaves",
      "legStyle": "boots",
      "auraStyle": "mist",
      "size": "small",
      "tilt": 2
    },
    "parts": [
      "body",
      "crest",
      "aura",
      "belly",
      "tail",
      "mouth",
      "horns",
      "cheeks",
      "spots",
      "legs",
      "eyes",
      "shadow_glow"
    ]
  },
  {
    "catalogId": "local-061",
    "name": "Moussipollena",
    "rarity": "wonder",
    "description": "Moussipollena est une créature toute ronde qui aime les mares brillantes et nage dans les reflets.",
    "personality": "curieuse et douce",
    "biome": "pond",
    "movementType": "swimming",
    "bodyShape": "round",
    "earShape": "leaf",
    "tailShape": "ribbon",
    "pattern": "spots",
    "palette": {
      "primary": "#8EE6C8",
      "secondary": "#F7D6FF",
      "accent": "#FFE66D",
      "dark": "#315C55"
    },
    "visuals": {
      "eyeStyle": "sparkle",
      "mouthStyle": "cat",
      "wingStyle": "none",
      "antennaStyle": "dots",
      "legStyle": "none",
      "auraStyle": "moon_glow",
      "size": "tiny",
      "tilt": -2
    },
    "parts": [
      "body",
      "cheeks",
      "ears",
      "horns",
      "wings",
      "antennae",
      "mouth",
      "sparkles",
      "tail",
      "shadow_glow",
      "belly",
      "eyes"
    ]
  },
  {
    "catalogId": "local-062",
    "name": "Brindipolleni",
    "rarity": "uncommon",
    "description": "Brindipolleni est une créature champignon qui aime les champignons doux et passe de la berge à l’eau.",
    "personality": "malicieuse mais très tendre",
    "biome": "mushroom_grove",
    "movementType": "amphibious",
    "bodyShape": "mushroom",
    "earShape": "tuft",
    "tailShape": "puff",
    "pattern": "stars",
    "palette": {
      "primary": "#A5D86A",
      "secondary": "#FFF1A8",
      "accent": "#FF9FB2",
      "dark": "#3C6134"
    },
    "visuals": {
      "eyeStyle": "crescent",
      "mouthStyle": "smile",
      "wingStyle": "leaf",
      "antennaStyle": "none",
      "legStyle": "leafy",
      "auraStyle": "sparkles",
      "size": "large",
      "tilt": -1
    },
    "parts": [
      "body",
      "eyes",
      "legs",
      "belly",
      "sparkles",
      "ears",
      "spots",
      "aura",
      "shadow_glow",
      "mouth",
      "wings",
      "cheeks"
    ]
  },
  {
    "catalogId": "local-063",
    "name": "Lumipolleno",
    "rarity": "common",
    "description": "Lumipolleno est une créature galet vivant qui aime les mares brillantes et marche à petits pas.",
    "personality": "rêveuse et calme",
    "biome": "pond",
    "movementType": "walking",
    "bodyShape": "pebble",
    "earShape": "fin",
    "tailShape": "star",
    "pattern": "none",
    "palette": {
      "primary": "#A4C8FF",
      "secondary": "#F2E6FF",
      "accent": "#FFD166",
      "dark": "#334767"
    },
    "visuals": {
      "eyeStyle": "glow",
      "mouthStyle": "beak",
      "wingStyle": "moth",
      "antennaStyle": "curl",
      "legStyle": "webbed",
      "auraStyle": "none",
      "size": "medium",
      "tilt": 0
    },
    "parts": [
      "body",
      "eyes",
      "aura",
      "tail",
      "cheeks",
      "legs",
      "shadow_glow",
      "antennae",
      "ears",
      "crest",
      "belly",
      "mouth"
    ]
  },
  {
    "catalogId": "local-064",
    "name": "Ploofpollenu",
    "rarity": "common",
    "description": "Ploofpollenu est une créature nuageuse qui aime les clairières de lune et sautille sans bruit.",
    "personality": "timide et brillante",
    "biome": "moon_clearing",
    "movementType": "hopping",
    "bodyShape": "cloud",
    "earShape": "round",
    "tailShape": "fin",
    "pattern": "freckles",
    "palette": {
      "primary": "#D9A7FF",
      "secondary": "#B8F2E6",
      "accent": "#FFCF70",
      "dark": "#4C3A68"
    },
    "visuals": {
      "eyeStyle": "sleepy",
      "mouthStyle": "tiny",
      "wingStyle": "none",
      "antennaStyle": "stars",
      "legStyle": "none",
      "auraStyle": "pollen",
      "size": "small",
      "tilt": 1
    },
    "parts": [
      "body",
      "eyes",
      "belly",
      "spots",
      "shadow_glow",
      "wings",
      "crest",
      "tail",
      "horns",
      "legs",
      "sparkles",
      "ears"
    ]
  },
  {
    "catalogId": "local-065",
    "name": "Nébulipollené",
    "rarity": "rare",
    "description": "Nébulipollené est une créature feuillue qui aime les champignons doux et vole lentement.",
    "personality": "joyeuse et sautillante",
    "biome": "mushroom_grove",
    "movementType": "flying",
    "bodyShape": "leaf",
    "earShape": "none",
    "tailShape": "curl",
    "pattern": "waves",
    "palette": {
      "primary": "#FFB7A3",
      "secondary": "#FFF3C4",
      "accent": "#8EE3EF",
      "dark": "#70403B"
    },
    "visuals": {
      "eyeStyle": "wide",
      "mouthStyle": "none",
      "wingStyle": "bubble",
      "antennaStyle": "leaves",
      "legStyle": "boots",
      "auraStyle": "bubbles",
      "size": "tiny",
      "tilt": 2
    },
    "parts": [
      "body",
      "eyes",
      "shadow_glow",
      "crest",
      "horns",
      "sparkles",
      "aura",
      "cheeks",
      "antennae",
      "belly",
      "spots",
      "wings"
    ]
  },
  {
    "catalogId": "local-066",
    "name": "Roselipollena",
    "rarity": "uncommon",
    "description": "Roselipollena est une créature étoilée qui aime les mares brillantes et flotte comme un rêve.",
    "personality": "bizarre juste comme il faut",
    "biome": "pond",
    "movementType": "floating",
    "bodyShape": "star",
    "earShape": "petal",
    "tailShape": "leaf",
    "pattern": "stripes",
    "palette": {
      "primary": "#7BDFF2",
      "secondary": "#C2F8CB",
      "accent": "#F7D794",
      "dark": "#28536B"
    },
    "visuals": {
      "eyeStyle": "dot",
      "mouthStyle": "cat",
      "wingStyle": "moth",
      "antennaStyle": "dots",
      "legStyle": "none",
      "auraStyle": "mist",
      "size": "large",
      "tilt": -2
    },
    "parts": [
      "body",
      "eyes",
      "mouth",
      "ears",
      "legs",
      "tail",
      "wings",
      "spots",
      "belly",
      "antennae",
      "cheeks",
      "aura"
    ]
  },
  {
    "catalogId": "local-067",
    "name": "Bamboupolleni",
    "rarity": "common",
    "description": "Bamboupolleni est une créature coquillage doux qui aime les mares brillantes et passe de la berge à l’eau.",
    "personality": "nocturne et rassurante",
    "biome": "pond",
    "movementType": "amphibious",
    "bodyShape": "shell",
    "earShape": "horns",
    "tailShape": "glow",
    "pattern": "leaf_veins",
    "palette": {
      "primary": "#B8E986",
      "secondary": "#E7FBBE",
      "accent": "#FFB6C1",
      "dark": "#365B2D"
    },
    "visuals": {
      "eyeStyle": "round",
      "mouthStyle": "smile",
      "wingStyle": "none",
      "antennaStyle": "none",
      "legStyle": "leafy",
      "auraStyle": "moon_glow",
      "size": "medium",
      "tilt": -1
    },
    "parts": [
      "body",
      "eyes",
      "mouth",
      "ears",
      "legs",
      "tail",
      "wings",
      "spots",
      "belly",
      "antennae",
      "cheeks",
      "aura"
    ]
  },
  {
    "catalogId": "local-068",
    "name": "Floripolleno",
    "rarity": "wonder",
    "description": "Floripolleno est une créature en forme de haricot qui aime les petits bois et marche à petits pas.",
    "personality": "gourmande de pollen",
    "biome": "forest",
    "movementType": "walking",
    "bodyShape": "bean",
    "earShape": "leaf",
    "tailShape": "none",
    "pattern": "moon",
    "palette": {
      "primary": "#CDB4DB",
      "secondary": "#FFC8DD",
      "accent": "#BDE0FE",
      "dark": "#4A3A57"
    },
    "visuals": {
      "eyeStyle": "sparkle",
      "mouthStyle": "beak",
      "wingStyle": "leaf",
      "antennaStyle": "curl",
      "legStyle": "webbed",
      "auraStyle": "sparkles",
      "size": "small",
      "tilt": 0
    },
    "parts": [
      "body",
      "antennae",
      "eyes",
      "cheeks",
      "mouth",
      "aura",
      "ears",
      "sparkles",
      "legs",
      "horns",
      "tail",
      "crest"
    ]
  },
  {
    "catalogId": "local-069",
    "name": "Dodupollenu",
    "rarity": "uncommon",
    "description": "Dodupollenu est une créature gouttelette qui aime les mares brillantes et sautille sans bruit.",
    "personality": "protectrice des petites pousses",
    "biome": "pond",
    "movementType": "hopping",
    "bodyShape": "droplet",
    "earShape": "tuft",
    "tailShape": "ribbon",
    "pattern": "rings",
    "palette": {
      "primary": "#F4A261",
      "secondary": "#E9C46A",
      "accent": "#2A9D8F",
      "dark": "#5A3A1E"
    },
    "visuals": {
      "eyeStyle": "crescent",
      "mouthStyle": "tiny",
      "wingStyle": "moth",
      "antennaStyle": "stars",
      "legStyle": "none",
      "auraStyle": "none",
      "size": "tiny",
      "tilt": 1
    },
    "parts": [
      "body",
      "wings",
      "sparkles",
      "eyes",
      "spots",
      "horns",
      "mouth",
      "belly",
      "crest",
      "ears",
      "antennae",
      "shadow_glow"
    ]
  },
  {
    "catalogId": "local-070",
    "name": "Ziboupollené",
    "rarity": "common",
    "description": "Ziboupollené est une créature toute longue qui aime les clairières de lune et vole lentement.",
    "personality": "amusante et jamais pressée",
    "biome": "moon_clearing",
    "movementType": "flying",
    "bodyShape": "long",
    "earShape": "fin",
    "tailShape": "puff",
    "pattern": "spots",
    "palette": {
      "primary": "#90BE6D",
      "secondary": "#F9C74F",
      "accent": "#577590",
      "dark": "#334E37"
    },
    "visuals": {
      "eyeStyle": "glow",
      "mouthStyle": "none",
      "wingStyle": "bubble",
      "antennaStyle": "leaves",
      "legStyle": "boots",
      "auraStyle": "pollen",
      "size": "large",
      "tilt": 2
    },
    "parts": [
      "body",
      "horns",
      "antennae",
      "tail",
      "eyes",
      "crest",
      "cheeks",
      "wings",
      "mouth",
      "shadow_glow",
      "aura",
      "spots"
    ]
  },
  {
    "catalogId": "local-071",
    "name": "Miropollena",
    "rarity": "common",
    "description": "Miropollena est une créature toute ronde qui aime les petits bois et flotte comme un rêve.",
    "personality": "curieuse et douce",
    "biome": "forest",
    "movementType": "floating",
    "bodyShape": "round",
    "earShape": "round",
    "tailShape": "star",
    "pattern": "stars",
    "palette": {
      "primary": "#C8E7FF",
      "secondary": "#FFF6BF",
      "accent": "#B392F0",
      "dark": "#2B3A67"
    },
    "visuals": {
      "eyeStyle": "sleepy",
      "mouthStyle": "cat",
      "wingStyle": "leaf",
      "antennaStyle": "dots",
      "legStyle": "none",
      "auraStyle": "bubbles",
      "size": "medium",
      "tilt": -2
    },
    "parts": [
      "body",
      "spots",
      "crest",
      "legs",
      "aura",
      "eyes",
      "belly",
      "shadow_glow",
      "tail",
      "sparkles",
      "mouth",
      "antennae"
    ]
  },
  {
    "catalogId": "local-072",
    "name": "Plumipolleni",
    "rarity": "rare",
    "description": "Plumipolleni est une créature champignon qui aime les mares brillantes et nage dans les reflets.",
    "personality": "malicieuse mais très tendre",
    "biome": "pond",
    "movementType": "swimming",
    "bodyShape": "mushroom",
    "earShape": "none",
    "tailShape": "fin",
    "pattern": "none",
    "palette": {
      "primary": "#A0E7E5",
      "secondary": "#B4F8C8",
      "accent": "#FBE7C6",
      "dark": "#28544B"
    },
    "visuals": {
      "eyeStyle": "wide",
      "mouthStyle": "smile",
      "wingStyle": "moth",
      "antennaStyle": "none",
      "legStyle": "none",
      "auraStyle": "mist",
      "size": "small",
      "tilt": -1
    },
    "parts": [
      "body",
      "ears",
      "wings",
      "antennae",
      "sparkles",
      "shadow_glow",
      "eyes",
      "legs",
      "spots",
      "cheeks",
      "horns",
      "mouth"
    ]
  },
  {
    "catalogId": "local-073",
    "name": "Tintipolleno",
    "rarity": "uncommon",
    "description": "Tintipolleno est une créature galet vivant qui aime les clairières de lune et marche à petits pas.",
    "personality": "rêveuse et calme",
    "biome": "moon_clearing",
    "movementType": "walking",
    "bodyShape": "pebble",
    "earShape": "petal",
    "tailShape": "curl",
    "pattern": "freckles",
    "palette": {
      "primary": "#F7A9A8",
      "secondary": "#FDE2E4",
      "accent": "#CDEAC0",
      "dark": "#643843"
    },
    "visuals": {
      "eyeStyle": "dot",
      "mouthStyle": "beak",
      "wingStyle": "none",
      "antennaStyle": "curl",
      "legStyle": "webbed",
      "auraStyle": "moon_glow",
      "size": "tiny",
      "tilt": 0
    },
    "parts": [
      "body",
      "tail",
      "cheeks",
      "shadow_glow",
      "ears",
      "belly",
      "horns",
      "eyes",
      "wings",
      "aura",
      "legs",
      "antennae"
    ]
  },
  {
    "catalogId": "local-074",
    "name": "Glimpollenu",
    "rarity": "common",
    "description": "Glimpollenu est une créature nuageuse qui aime les petits bois et sautille sans bruit.",
    "personality": "timide et brillante",
    "biome": "forest",
    "movementType": "hopping",
    "bodyShape": "cloud",
    "earShape": "horns",
    "tailShape": "leaf",
    "pattern": "waves",
    "palette": {
      "primary": "#9D4EDD",
      "secondary": "#E0AAFF",
      "accent": "#80FFDB",
      "dark": "#3C096C"
    },
    "visuals": {
      "eyeStyle": "round",
      "mouthStyle": "tiny",
      "wingStyle": "leaf",
      "antennaStyle": "stars",
      "legStyle": "none",
      "auraStyle": "sparkles",
      "size": "large",
      "tilt": 1
    },
    "parts": [
      "body",
      "shadow_glow",
      "horns",
      "aura",
      "antennae",
      "spots",
      "tail",
      "ears",
      "eyes",
      "crest",
      "sparkles",
      "cheeks"
    ]
  },
  {
    "catalogId": "local-075",
    "name": "Mallowpollené",
    "rarity": "wonder",
    "description": "Mallowpollené est une créature feuillue qui aime les fleurs hautes et vole lentement.",
    "personality": "joyeuse et sautillante",
    "biome": "meadow",
    "movementType": "flying",
    "bodyShape": "leaf",
    "earShape": "leaf",
    "tailShape": "glow",
    "pattern": "stripes",
    "palette": {
      "primary": "#577590",
      "secondary": "#F3CA40",
      "accent": "#F2A541",
      "dark": "#25364A"
    },
    "visuals": {
      "eyeStyle": "sparkle",
      "mouthStyle": "none",
      "wingStyle": "bubble",
      "antennaStyle": "leaves",
      "legStyle": "boots",
      "auraStyle": "none",
      "size": "medium",
      "tilt": 2
    },
    "parts": [
      "body",
      "mouth",
      "legs",
      "wings",
      "belly",
      "cheeks",
      "sparkles",
      "crest",
      "eyes",
      "ears",
      "tail",
      "spots"
    ]
  },
  {
    "catalogId": "local-076",
    "name": "Froupollena",
    "rarity": "uncommon",
    "description": "Froupollena est une créature étoilée qui aime les champignons doux et flotte comme un rêve.",
    "personality": "bizarre juste comme il faut",
    "biome": "mushroom_grove",
    "movementType": "floating",
    "bodyShape": "star",
    "earShape": "tuft",
    "tailShape": "none",
    "pattern": "leaf_veins",
    "palette": {
      "primary": "#84DCC6",
      "secondary": "#A5FFD6",
      "accent": "#FFA69E",
      "dark": "#355C55"
    },
    "visuals": {
      "eyeStyle": "crescent",
      "mouthStyle": "cat",
      "wingStyle": "none",
      "antennaStyle": "dots",
      "legStyle": "none",
      "auraStyle": "pollen",
      "size": "small",
      "tilt": -2
    },
    "parts": [
      "body",
      "sparkles",
      "spots",
      "mouth",
      "crest",
      "antennae",
      "legs",
      "aura",
      "wings",
      "eyes",
      "horns",
      "belly"
    ]
  },
  {
    "catalogId": "local-077",
    "name": "Sissipolleni",
    "rarity": "common",
    "description": "Sissipolleni est une créature coquillage doux qui aime les mares brillantes et nage dans les reflets.",
    "personality": "nocturne et rassurante",
    "biome": "pond",
    "movementType": "swimming",
    "bodyShape": "shell",
    "earShape": "fin",
    "tailShape": "ribbon",
    "pattern": "moon",
    "palette": {
      "primary": "#BFD7EA",
      "secondary": "#F5E6E8",
      "accent": "#F4B860",
      "dark": "#2F4858"
    },
    "visuals": {
      "eyeStyle": "glow",
      "mouthStyle": "smile",
      "wingStyle": "leaf",
      "antennaStyle": "none",
      "legStyle": "none",
      "auraStyle": "bubbles",
      "size": "tiny",
      "tilt": -1
    },
    "parts": [
      "body",
      "crest",
      "aura",
      "belly",
      "tail",
      "mouth",
      "horns",
      "cheeks",
      "spots",
      "legs",
      "eyes",
      "shadow_glow"
    ]
  },
  {
    "catalogId": "local-078",
    "name": "Blooppolleno",
    "rarity": "common",
    "description": "Blooppolleno est une créature en forme de haricot qui aime les fleurs hautes et passe de la berge à l’eau.",
    "personality": "gourmande de pollen",
    "biome": "meadow",
    "movementType": "amphibious",
    "bodyShape": "bean",
    "earShape": "round",
    "tailShape": "puff",
    "pattern": "rings",
    "palette": {
      "primary": "#D0F4DE",
      "secondary": "#FCF6BD",
      "accent": "#A9DEF9",
      "dark": "#3E5C43"
    },
    "visuals": {
      "eyeStyle": "sleepy",
      "mouthStyle": "beak",
      "wingStyle": "moth",
      "antennaStyle": "curl",
      "legStyle": "webbed",
      "auraStyle": "mist",
      "size": "large",
      "tilt": 0
    },
    "parts": [
      "body",
      "cheeks",
      "ears",
      "horns",
      "wings",
      "antennae",
      "mouth",
      "sparkles",
      "tail",
      "shadow_glow",
      "belly",
      "eyes"
    ]
  },
  {
    "catalogId": "local-079",
    "name": "Noctipollenu",
    "rarity": "rare",
    "description": "Noctipollenu est une créature gouttelette qui aime les champignons doux et sautille sans bruit.",
    "personality": "protectrice des petites pousses",
    "biome": "mushroom_grove",
    "movementType": "hopping",
    "bodyShape": "droplet",
    "earShape": "none",
    "tailShape": "star",
    "pattern": "spots",
    "palette": {
      "primary": "#E4C1F9",
      "secondary": "#F694C1",
      "accent": "#EDE7B1",
      "dark": "#543864"
    },
    "visuals": {
      "eyeStyle": "wide",
      "mouthStyle": "tiny",
      "wingStyle": "none",
      "antennaStyle": "stars",
      "legStyle": "none",
      "auraStyle": "moon_glow",
      "size": "medium",
      "tilt": 1
    },
    "parts": [
      "body",
      "eyes",
      "legs",
      "belly",
      "sparkles",
      "ears",
      "spots",
      "aura",
      "shadow_glow",
      "mouth",
      "wings",
      "cheeks"
    ]
  },
  {
    "catalogId": "local-080",
    "name": "Pépipollené",
    "rarity": "uncommon",
    "description": "Pépipollené est une créature toute longue qui aime les mares brillantes et vole lentement.",
    "personality": "amusante et jamais pressée",
    "biome": "pond",
    "movementType": "flying",
    "bodyShape": "long",
    "earShape": "petal",
    "tailShape": "fin",
    "pattern": "stars",
    "palette": {
      "primary": "#CDE7BE",
      "secondary": "#F3FFBD",
      "accent": "#FFB3C1",
      "dark": "#3B5B42"
    },
    "visuals": {
      "eyeStyle": "dot",
      "mouthStyle": "none",
      "wingStyle": "bubble",
      "antennaStyle": "leaves",
      "legStyle": "boots",
      "auraStyle": "sparkles",
      "size": "small",
      "tilt": 2
    },
    "parts": [
      "body",
      "eyes",
      "aura",
      "tail",
      "cheeks",
      "legs",
      "shadow_glow",
      "antennae",
      "ears",
      "crest",
      "belly",
      "mouth"
    ]
  },
  {
    "catalogId": "local-081",
    "name": "Moussidouxa",
    "rarity": "common",
    "description": "Moussidouxa est une créature toute ronde qui aime les fleurs hautes et flotte comme un rêve.",
    "personality": "curieuse et douce",
    "biome": "meadow",
    "movementType": "floating",
    "bodyShape": "round",
    "earShape": "horns",
    "tailShape": "curl",
    "pattern": "none",
    "palette": {
      "primary": "#8EE6C8",
      "secondary": "#F7D6FF",
      "accent": "#FFE66D",
      "dark": "#315C55"
    },
    "visuals": {
      "eyeStyle": "round",
      "mouthStyle": "cat",
      "wingStyle": "moth",
      "antennaStyle": "dots",
      "legStyle": "none",
      "auraStyle": "none",
      "size": "tiny",
      "tilt": -2
    },
    "parts": [
      "body",
      "eyes",
      "belly",
      "spots",
      "shadow_glow",
      "wings",
      "crest",
      "tail",
      "horns",
      "legs",
      "sparkles",
      "ears"
    ]
  },
  {
    "catalogId": "local-082",
    "name": "Brindidouxi",
    "rarity": "wonder",
    "description": "Brindidouxi est une créature champignon qui aime les mares brillantes et nage dans les reflets.",
    "personality": "malicieuse mais très tendre",
    "biome": "pond",
    "movementType": "swimming",
    "bodyShape": "mushroom",
    "earShape": "leaf",
    "tailShape": "leaf",
    "pattern": "freckles",
    "palette": {
      "primary": "#A5D86A",
      "secondary": "#FFF1A8",
      "accent": "#FF9FB2",
      "dark": "#3C6134"
    },
    "visuals": {
      "eyeStyle": "sparkle",
      "mouthStyle": "smile",
      "wingStyle": "none",
      "antennaStyle": "none",
      "legStyle": "none",
      "auraStyle": "pollen",
      "size": "large",
      "tilt": -1
    },
    "parts": [
      "body",
      "eyes",
      "shadow_glow",
      "crest",
      "horns",
      "sparkles",
      "aura",
      "cheeks",
      "antennae",
      "belly",
      "spots",
      "wings"
    ]
  },
  {
    "catalogId": "local-083",
    "name": "Lumidouxo",
    "rarity": "uncommon",
    "description": "Lumidouxo est une créature galet vivant qui aime les mares brillantes et passe de la berge à l’eau.",
    "personality": "rêveuse et calme",
    "biome": "pond",
    "movementType": "amphibious",
    "bodyShape": "pebble",
    "earShape": "tuft",
    "tailShape": "glow",
    "pattern": "waves",
    "palette": {
      "primary": "#A4C8FF",
      "secondary": "#F2E6FF",
      "accent": "#FFD166",
      "dark": "#334767"
    },
    "visuals": {
      "eyeStyle": "crescent",
      "mouthStyle": "beak",
      "wingStyle": "leaf",
      "antennaStyle": "curl",
      "legStyle": "webbed",
      "auraStyle": "bubbles",
      "size": "medium",
      "tilt": 0
    },
    "parts": [
      "body",
      "eyes",
      "mouth",
      "ears",
      "legs",
      "tail",
      "wings",
      "spots",
      "belly",
      "antennae",
      "cheeks",
      "aura"
    ]
  },
  {
    "catalogId": "local-084",
    "name": "Ploofdouxu",
    "rarity": "common",
    "description": "Ploofdouxu est une créature nuageuse qui aime les clairières de lune et marche à petits pas.",
    "personality": "timide et brillante",
    "biome": "moon_clearing",
    "movementType": "walking",
    "bodyShape": "cloud",
    "earShape": "fin",
    "tailShape": "none",
    "pattern": "stripes",
    "palette": {
      "primary": "#D9A7FF",
      "secondary": "#B8F2E6",
      "accent": "#FFCF70",
      "dark": "#4C3A68"
    },
    "visuals": {
      "eyeStyle": "glow",
      "mouthStyle": "tiny",
      "wingStyle": "moth",
      "antennaStyle": "stars",
      "legStyle": "none",
      "auraStyle": "mist",
      "size": "small",
      "tilt": 1
    },
    "parts": [
      "body",
      "eyes",
      "mouth",
      "ears",
      "legs",
      "tail",
      "wings",
      "spots",
      "belly",
      "antennae",
      "cheeks",
      "aura"
    ]
  },
  {
    "catalogId": "local-085",
    "name": "Nébulidouxé",
    "rarity": "common",
    "description": "Nébulidouxé est une créature feuillue qui aime les champignons doux et vole lentement.",
    "personality": "joyeuse et sautillante",
    "biome": "mushroom_grove",
    "movementType": "flying",
    "bodyShape": "leaf",
    "earShape": "round",
    "tailShape": "ribbon",
    "pattern": "leaf_veins",
    "palette": {
      "primary": "#FFB7A3",
      "secondary": "#FFF3C4",
      "accent": "#8EE3EF",
      "dark": "#70403B"
    },
    "visuals": {
      "eyeStyle": "sleepy",
      "mouthStyle": "none",
      "wingStyle": "bubble",
      "antennaStyle": "leaves",
      "legStyle": "boots",
      "auraStyle": "moon_glow",
      "size": "tiny",
      "tilt": 2
    },
    "parts": [
      "body",
      "antennae",
      "eyes",
      "cheeks",
      "mouth",
      "aura",
      "ears",
      "sparkles",
      "legs",
      "horns",
      "tail",
      "crest"
    ]
  },
  {
    "catalogId": "local-086",
    "name": "Roselidouxa",
    "rarity": "rare",
    "description": "Roselidouxa est une créature étoilée qui aime les mares brillantes et flotte comme un rêve.",
    "personality": "bizarre juste comme il faut",
    "biome": "pond",
    "movementType": "floating",
    "bodyShape": "star",
    "earShape": "none",
    "tailShape": "puff",
    "pattern": "moon",
    "palette": {
      "primary": "#7BDFF2",
      "secondary": "#C2F8CB",
      "accent": "#F7D794",
      "dark": "#28536B"
    },
    "visuals": {
      "eyeStyle": "wide",
      "mouthStyle": "cat",
      "wingStyle": "leaf",
      "antennaStyle": "dots",
      "legStyle": "none",
      "auraStyle": "sparkles",
      "size": "large",
      "tilt": -2
    },
    "parts": [
      "body",
      "wings",
      "sparkles",
      "eyes",
      "spots",
      "horns",
      "mouth",
      "belly",
      "crest",
      "ears",
      "antennae",
      "shadow_glow"
    ]
  },
  {
    "catalogId": "local-087",
    "name": "Bamboudouxi",
    "rarity": "uncommon",
    "description": "Bamboudouxi est une créature coquillage doux qui aime les mares brillantes et nage dans les reflets.",
    "personality": "nocturne et rassurante",
    "biome": "pond",
    "movementType": "swimming",
    "bodyShape": "shell",
    "earShape": "petal",
    "tailShape": "star",
    "pattern": "rings",
    "palette": {
      "primary": "#B8E986",
      "secondary": "#E7FBBE",
      "accent": "#FFB6C1",
      "dark": "#365B2D"
    },
    "visuals": {
      "eyeStyle": "dot",
      "mouthStyle": "smile",
      "wingStyle": "moth",
      "antennaStyle": "none",
      "legStyle": "none",
      "auraStyle": "none",
      "size": "medium",
      "tilt": -1
    },
    "parts": [
      "body",
      "horns",
      "antennae",
      "tail",
      "eyes",
      "crest",
      "cheeks",
      "wings",
      "mouth",
      "shadow_glow",
      "aura",
      "spots"
    ]
  },
  {
    "catalogId": "local-088",
    "name": "Floridouxo",
    "rarity": "common",
    "description": "Floridouxo est une créature en forme de haricot qui aime les petits bois et passe de la berge à l’eau.",
    "personality": "gourmande de pollen",
    "biome": "forest",
    "movementType": "amphibious",
    "bodyShape": "bean",
    "earShape": "horns",
    "tailShape": "fin",
    "pattern": "spots",
    "palette": {
      "primary": "#CDB4DB",
      "secondary": "#FFC8DD",
      "accent": "#BDE0FE",
      "dark": "#4A3A57"
    },
    "visuals": {
      "eyeStyle": "round",
      "mouthStyle": "beak",
      "wingStyle": "none",
      "antennaStyle": "curl",
      "legStyle": "webbed",
      "auraStyle": "pollen",
      "size": "small",
      "tilt": 0
    },
    "parts": [
      "body",
      "spots",
      "crest",
      "legs",
      "aura",
      "eyes",
      "belly",
      "shadow_glow",
      "tail",
      "sparkles",
      "mouth",
      "antennae"
    ]
  },
  {
    "catalogId": "local-089",
    "name": "Dodudouxu",
    "rarity": "wonder",
    "description": "Dodudouxu est une créature gouttelette qui aime les mares brillantes et marche à petits pas.",
    "personality": "protectrice des petites pousses",
    "biome": "pond",
    "movementType": "walking",
    "bodyShape": "droplet",
    "earShape": "leaf",
    "tailShape": "curl",
    "pattern": "stars",
    "palette": {
      "primary": "#F4A261",
      "secondary": "#E9C46A",
      "accent": "#2A9D8F",
      "dark": "#5A3A1E"
    },
    "visuals": {
      "eyeStyle": "sparkle",
      "mouthStyle": "tiny",
      "wingStyle": "leaf",
      "antennaStyle": "stars",
      "legStyle": "none",
      "auraStyle": "bubbles",
      "size": "tiny",
      "tilt": 1
    },
    "parts": [
      "body",
      "ears",
      "wings",
      "antennae",
      "sparkles",
      "shadow_glow",
      "eyes",
      "legs",
      "spots",
      "cheeks",
      "horns",
      "mouth"
    ]
  },
  {
    "catalogId": "local-090",
    "name": "Ziboudouxé",
    "rarity": "uncommon",
    "description": "Ziboudouxé est une créature toute longue qui aime les clairières de lune et sautille sans bruit.",
    "personality": "amusante et jamais pressée",
    "biome": "moon_clearing",
    "movementType": "hopping",
    "bodyShape": "long",
    "earShape": "tuft",
    "tailShape": "leaf",
    "pattern": "none",
    "palette": {
      "primary": "#90BE6D",
      "secondary": "#F9C74F",
      "accent": "#577590",
      "dark": "#334E37"
    },
    "visuals": {
      "eyeStyle": "crescent",
      "mouthStyle": "none",
      "wingStyle": "moth",
      "antennaStyle": "leaves",
      "legStyle": "boots",
      "auraStyle": "mist",
      "size": "large",
      "tilt": 2
    },
    "parts": [
      "body",
      "tail",
      "cheeks",
      "shadow_glow",
      "ears",
      "belly",
      "horns",
      "eyes",
      "wings",
      "aura",
      "legs",
      "antennae"
    ]
  },
  {
    "catalogId": "local-091",
    "name": "Mirodouxa",
    "rarity": "common",
    "description": "Mirodouxa est une créature toute ronde qui aime les petits bois et flotte comme un rêve.",
    "personality": "curieuse et douce",
    "biome": "forest",
    "movementType": "floating",
    "bodyShape": "round",
    "earShape": "fin",
    "tailShape": "glow",
    "pattern": "freckles",
    "palette": {
      "primary": "#C8E7FF",
      "secondary": "#FFF6BF",
      "accent": "#B392F0",
      "dark": "#2B3A67"
    },
    "visuals": {
      "eyeStyle": "glow",
      "mouthStyle": "cat",
      "wingStyle": "none",
      "antennaStyle": "dots",
      "legStyle": "none",
      "auraStyle": "moon_glow",
      "size": "medium",
      "tilt": -2
    },
    "parts": [
      "body",
      "shadow_glow",
      "horns",
      "aura",
      "antennae",
      "spots",
      "tail",
      "ears",
      "eyes",
      "crest",
      "sparkles",
      "cheeks"
    ]
  },
  {
    "catalogId": "local-092",
    "name": "Plumidouxi",
    "rarity": "common",
    "description": "Plumidouxi est une créature champignon qui aime les mares brillantes et nage dans les reflets.",
    "personality": "malicieuse mais très tendre",
    "biome": "pond",
    "movementType": "swimming",
    "bodyShape": "mushroom",
    "earShape": "round",
    "tailShape": "none",
    "pattern": "waves",
    "palette": {
      "primary": "#A0E7E5",
      "secondary": "#B4F8C8",
      "accent": "#FBE7C6",
      "dark": "#28544B"
    },
    "visuals": {
      "eyeStyle": "sleepy",
      "mouthStyle": "smile",
      "wingStyle": "leaf",
      "antennaStyle": "none",
      "legStyle": "none",
      "auraStyle": "sparkles",
      "size": "small",
      "tilt": -1
    },
    "parts": [
      "body",
      "mouth",
      "legs",
      "wings",
      "belly",
      "cheeks",
      "sparkles",
      "crest",
      "eyes",
      "ears",
      "tail",
      "spots"
    ]
  },
  {
    "catalogId": "local-093",
    "name": "Tintidouxo",
    "rarity": "rare",
    "description": "Tintidouxo est une créature galet vivant qui aime les mares brillantes et passe de la berge à l’eau.",
    "personality": "rêveuse et calme",
    "biome": "pond",
    "movementType": "amphibious",
    "bodyShape": "pebble",
    "earShape": "none",
    "tailShape": "ribbon",
    "pattern": "stripes",
    "palette": {
      "primary": "#F7A9A8",
      "secondary": "#FDE2E4",
      "accent": "#CDEAC0",
      "dark": "#643843"
    },
    "visuals": {
      "eyeStyle": "wide",
      "mouthStyle": "beak",
      "wingStyle": "moth",
      "antennaStyle": "curl",
      "legStyle": "webbed",
      "auraStyle": "none",
      "size": "tiny",
      "tilt": 0
    },
    "parts": [
      "body",
      "sparkles",
      "spots",
      "mouth",
      "crest",
      "antennae",
      "legs",
      "aura",
      "wings",
      "eyes",
      "horns",
      "belly"
    ]
  },
  {
    "catalogId": "local-094",
    "name": "Glimdouxu",
    "rarity": "uncommon",
    "description": "Glimdouxu est une créature nuageuse qui aime les petits bois et marche à petits pas.",
    "personality": "timide et brillante",
    "biome": "forest",
    "movementType": "walking",
    "bodyShape": "cloud",
    "earShape": "petal",
    "tailShape": "puff",
    "pattern": "leaf_veins",
    "palette": {
      "primary": "#9D4EDD",
      "secondary": "#E0AAFF",
      "accent": "#80FFDB",
      "dark": "#3C096C"
    },
    "visuals": {
      "eyeStyle": "dot",
      "mouthStyle": "tiny",
      "wingStyle": "none",
      "antennaStyle": "stars",
      "legStyle": "none",
      "auraStyle": "pollen",
      "size": "large",
      "tilt": 1
    },
    "parts": [
      "body",
      "crest",
      "aura",
      "belly",
      "tail",
      "mouth",
      "horns",
      "cheeks",
      "spots",
      "legs",
      "eyes",
      "shadow_glow"
    ]
  },
  {
    "catalogId": "local-095",
    "name": "Mallowdouxé",
    "rarity": "common",
    "description": "Mallowdouxé est une créature feuillue qui aime les fleurs hautes et sautille sans bruit.",
    "personality": "joyeuse et sautillante",
    "biome": "meadow",
    "movementType": "hopping",
    "bodyShape": "leaf",
    "earShape": "horns",
    "tailShape": "star",
    "pattern": "moon",
    "palette": {
      "primary": "#577590",
      "secondary": "#F3CA40",
      "accent": "#F2A541",
      "dark": "#25364A"
    },
    "visuals": {
      "eyeStyle": "round",
      "mouthStyle": "none",
      "wingStyle": "leaf",
      "antennaStyle": "leaves",
      "legStyle": "boots",
      "auraStyle": "bubbles",
      "size": "medium",
      "tilt": 2
    },
    "parts": [
      "body",
      "cheeks",
      "ears",
      "horns",
      "wings",
      "antennae",
      "mouth",
      "sparkles",
      "tail",
      "shadow_glow",
      "belly",
      "eyes"
    ]
  },
  {
    "catalogId": "local-096",
    "name": "Froudouxa",
    "rarity": "wonder",
    "description": "Froudouxa est une créature étoilée qui aime les champignons doux et vole lentement.",
    "personality": "bizarre juste comme il faut",
    "biome": "mushroom_grove",
    "movementType": "flying",
    "bodyShape": "star",
    "earShape": "leaf",
    "tailShape": "fin",
    "pattern": "rings",
    "palette": {
      "primary": "#84DCC6",
      "secondary": "#A5FFD6",
      "accent": "#FFA69E",
      "dark": "#355C55"
    },
    "visuals": {
      "eyeStyle": "sparkle",
      "mouthStyle": "cat",
      "wingStyle": "small",
      "antennaStyle": "dots",
      "legStyle": "tiny",
      "auraStyle": "mist",
      "size": "small",
      "tilt": -2
    },
    "parts": [
      "body",
      "eyes",
      "legs",
      "belly",
      "sparkles",
      "ears",
      "spots",
      "aura",
      "shadow_glow",
      "mouth",
      "wings",
      "cheeks"
    ]
  },
  {
    "catalogId": "local-097",
    "name": "Sissidouxi",
    "rarity": "uncommon",
    "description": "Sissidouxi est une créature coquillage doux qui aime les mares brillantes et nage dans les reflets.",
    "personality": "nocturne et rassurante",
    "biome": "pond",
    "movementType": "swimming",
    "bodyShape": "shell",
    "earShape": "tuft",
    "tailShape": "curl",
    "pattern": "spots",
    "palette": {
      "primary": "#BFD7EA",
      "secondary": "#F5E6E8",
      "accent": "#F4B860",
      "dark": "#2F4858"
    },
    "visuals": {
      "eyeStyle": "crescent",
      "mouthStyle": "smile",
      "wingStyle": "none",
      "antennaStyle": "none",
      "legStyle": "none",
      "auraStyle": "moon_glow",
      "size": "tiny",
      "tilt": -1
    },
    "parts": [
      "body",
      "eyes",
      "aura",
      "tail",
      "cheeks",
      "legs",
      "shadow_glow",
      "antennae",
      "ears",
      "crest",
      "belly",
      "mouth"
    ]
  },
  {
    "catalogId": "local-098",
    "name": "Bloopdouxo",
    "rarity": "common",
    "description": "Bloopdouxo est une créature en forme de haricot qui aime les fleurs hautes et passe de la berge à l’eau.",
    "personality": "gourmande de pollen",
    "biome": "meadow",
    "movementType": "amphibious",
    "bodyShape": "bean",
    "earShape": "fin",
    "tailShape": "leaf",
    "pattern": "stars",
    "palette": {
      "primary": "#D0F4DE",
      "secondary": "#FCF6BD",
      "accent": "#A9DEF9",
      "dark": "#3E5C43"
    },
    "visuals": {
      "eyeStyle": "glow",
      "mouthStyle": "beak",
      "wingStyle": "leaf",
      "antennaStyle": "curl",
      "legStyle": "webbed",
      "auraStyle": "sparkles",
      "size": "large",
      "tilt": 0
    },
    "parts": [
      "body",
      "eyes",
      "belly",
      "spots",
      "shadow_glow",
      "wings",
      "crest",
      "tail",
      "horns",
      "legs",
      "sparkles",
      "ears"
    ]
  },
  {
    "catalogId": "local-099",
    "name": "Noctidouxu",
    "rarity": "common",
    "description": "Noctidouxu est une créature gouttelette qui aime les champignons doux et marche à petits pas.",
    "personality": "protectrice des petites pousses",
    "biome": "mushroom_grove",
    "movementType": "walking",
    "bodyShape": "droplet",
    "earShape": "round",
    "tailShape": "glow",
    "pattern": "none",
    "palette": {
      "primary": "#E4C1F9",
      "secondary": "#F694C1",
      "accent": "#EDE7B1",
      "dark": "#543864"
    },
    "visuals": {
      "eyeStyle": "sleepy",
      "mouthStyle": "tiny",
      "wingStyle": "moth",
      "antennaStyle": "stars",
      "legStyle": "none",
      "auraStyle": "none",
      "size": "medium",
      "tilt": 1
    },
    "parts": [
      "body",
      "eyes",
      "shadow_glow",
      "crest",
      "horns",
      "sparkles",
      "aura",
      "cheeks",
      "antennae",
      "belly",
      "spots",
      "wings"
    ]
  },
  {
    "catalogId": "local-100",
    "name": "Pépidouxé",
    "rarity": "rare",
    "description": "Pépidouxé est une créature toute longue qui aime les mares brillantes et sautille sans bruit.",
    "personality": "amusante et jamais pressée",
    "biome": "pond",
    "movementType": "hopping",
    "bodyShape": "long",
    "earShape": "none",
    "tailShape": "none",
    "pattern": "freckles",
    "palette": {
      "primary": "#CDE7BE",
      "secondary": "#F3FFBD",
      "accent": "#FFB3C1",
      "dark": "#3B5B42"
    },
    "visuals": {
      "eyeStyle": "wide",
      "mouthStyle": "none",
      "wingStyle": "none",
      "antennaStyle": "leaves",
      "legStyle": "boots",
      "auraStyle": "pollen",
      "size": "small",
      "tilt": 2
    },
    "parts": [
      "body",
      "eyes",
      "mouth",
      "ears",
      "legs",
      "tail",
      "wings",
      "spots",
      "belly",
      "antennae",
      "cheeks",
      "aura"
    ]
  }
] satisfies LocalCreatureBlueprint[]
